/**
 * THEMELI — Core namespace and constants
 */

// ========== I18N ==========
const LANG = window.location.pathname.includes('/el/') ? 'el' : 'en';
const BASE = window.location.pathname.match(/\/(en|el)\//) ? '../' : '';

/* THEMELI — Supabase client */

// Supabase client (read-only, uses anon key)
const _sb = (typeof SUPABASE_URL !== 'undefined' && typeof supabase !== 'undefined')
  ? supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
  : null;

// Shared async fetch: Supabase → fallback to PROJECTS constant
async function fetchProjects() {
  if (_sb) {
    try {
      const { data, error } = await _sb.from('projects').select('*').order('id');
      if (!error && data) {
        return data.map(r => ({
          id: r.id, name: r.name, description: r.description || '',
          year: r.year, typology: r.typology, location: r.location || '',
          architect: r.architect || '', size: r.size || '',
          status: r.status || 'Completed', dateCompleted: r.date_completed || '',
          image: r.image_url || '', mapX: r.map_x, mapY: r.map_y
        }));
      }
    } catch (e) { /* fall through to local data */ }
  }
  return typeof PROJECTS !== 'undefined' ? PROJECTS : [];
}

/* THEMELI — Internationalization data */

// UI strings (non-content translations)
const I18N = {
  en: {
    projects: 'Projects', project: 'Project',
    copied: 'Copied!', copyAddress: 'Copy Address', copyNumber: 'Copy Number'
  },
  el: {
    projects: 'Έργα', project: 'Έργο',
    copied: 'Αντιγράφηκε!', copyAddress: 'Αντιγραφή Διεύθυνσης', copyNumber: 'Αντιγραφή Αριθμού'
  }
};
const T = I18N[LANG];

// Subsidiary data loaded from external subsidiaries-data.js (generated by build)
// Prepend BASE to all asset paths at runtime
function prefixSubsPaths(data) {
  if (!data || !BASE) return data;
  const result = {};
  for (const [key, sub] of Object.entries(data)) {
    const s = JSON.parse(JSON.stringify(sub)); // deep clone
    if (s.logo) s.logo = BASE + s.logo;
    if (s.featured) {
      s.featured.forEach(f => { if (f.img) f.img = BASE + f.img; });
    }
    if (s.featuredGroups) {
      s.featuredGroups.forEach(g => {
        if (g.items) g.items.forEach(f => { if (f.img) f.img = BASE + f.img; });
        if (g.gallery) g.gallery = g.gallery.map(p => BASE + p);
      });
    }
    result[key] = s;
  }
  return result;
}

// Attach subsData to T for backward compatibility with subsidiaries page
const rawSubsData = (typeof SUBS_DATA !== 'undefined') ? SUBS_DATA[LANG] : {};
T.subsData = prefixSubsPaths(rawSubsData);

// Language switcher
const langSwitch = document.querySelector('[data-lang-switch]');
if (langSwitch) {
  const otherLang = LANG === 'en' ? 'el' : 'en';
  const currentPath = window.location.pathname;
  const newPath = currentPath.replace('/' + LANG + '/', '/' + otherLang + '/');
  langSwitch.href = newPath + window.location.search;
}

/* THEMELI — Menu & navigation */

// ========== MENU ==========
const hamburger = document.getElementById('hamburger');
const navOverlay = document.getElementById('navOverlay');

if (hamburger && navOverlay) {
  const mainContent = document.querySelector('main');
  const footer = document.querySelector('footer');

  function openMenu() {
    hamburger.classList.add('is-active');
    navOverlay.classList.add('is-open');
    hamburger.setAttribute('aria-expanded', 'true');
    document.body.style.overflow = 'hidden';
    // Focus trap: make main/footer inert
    if (mainContent) mainContent.setAttribute('inert', '');
    if (footer) footer.setAttribute('inert', '');
  }

  function closeMenu() {
    hamburger.classList.remove('is-active');
    navOverlay.classList.remove('is-open');
    hamburger.setAttribute('aria-expanded', 'false');
    document.body.style.overflow = '';
    // Remove focus trap
    if (mainContent) mainContent.removeAttribute('inert');
    if (footer) footer.removeAttribute('inert');
    hamburger.focus();
  }

  hamburger.addEventListener('click', () => {
    if (navOverlay.classList.contains('is-open')) {
      closeMenu();
    } else {
      openMenu();
    }
  });

  navOverlay.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', () => {
      closeMenu();
    });
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && navOverlay.classList.contains('is-open')) {
      closeMenu();
    }
  });
}

/* THEMELI — Scroll reveal animations */

// ========== SCROLL REVEAL ==========
const revealObserver = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('is-visible');
    }
  });
}, {
  threshold: 0.1,
  rootMargin: '0px 0px -60px 0px'
});

document.querySelectorAll('.reveal, .reveal-left, .reveal-right, .reveal-scale, .timeline-bar').forEach(el => {
  revealObserver.observe(el);
});

/* THEMELI — Typewriter effect */

// ========== TYPEWRITER EFFECT ==========
document.querySelectorAll('.timeline-opener').forEach(el => {
  const origHTML = el.innerHTML;
  el.classList.add('typewriter');

  // Parse original HTML into a temp container
  const temp = document.createElement('div');
  temp.innerHTML = origHTML;

  const walkAndWrap = (node) => {
    const frag = document.createDocumentFragment();
    node.childNodes.forEach(child => {
      if (child.nodeType === Node.TEXT_NODE) {
        child.textContent.split('').forEach(ch => {
          const span = document.createElement('span');
          span.className = 'tw-char';
          span.textContent = ch;
          frag.appendChild(span);
        });
      } else if (child.nodeType === Node.ELEMENT_NODE) {
        const clone = child.cloneNode(false);
        clone.appendChild(walkAndWrap(child));
        frag.appendChild(clone);
      }
    });
    return frag;
  };

  el.innerHTML = '';
  el.appendChild(walkAndWrap(temp));

  // Gather all tw-char spans in order
  const chars = el.querySelectorAll('.tw-char');

  // Observe for scroll reveal
  const twObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        twObserver.unobserve(el);
        el.classList.add('typing');
        let i = 0;
        const speed = 14; // ms per batch
        const batchSize = 2; // reveal 2 chars per tick
        const tick = () => {
          if (i < chars.length) {
            for (let b = 0; b < batchSize && i < chars.length; b++, i++) {
              chars[i].classList.add('tw-visible');
            }
            requestAnimationFrame(() => setTimeout(tick, speed));
          }
        };
        tick();
      }
    });
  }, { threshold: 0.1 });

  twObserver.observe(el);
});

/* THEMELI — Scroll utilities */

// ========== PAGE HEADER SCROLL FADE ==========
const pageHeader = document.querySelector('.page-header');
if (pageHeader) {
  let phTicking = false;
  let phLastScrollY = 0;
  window.addEventListener('scroll', () => {
    if (!phTicking) {
      requestAnimationFrame(() => {
        const currentY = window.scrollY;
        if (currentY <= 80) {
          pageHeader.classList.remove('is-hidden');
        } else if (currentY < phLastScrollY) {
          pageHeader.classList.remove('is-hidden');
        } else {
          pageHeader.classList.add('is-hidden');
        }
        phLastScrollY = currentY;
        phTicking = false;
      });
      phTicking = true;
    }
  }, { passive: true });
}

// ========== SCROLL TO TOP ==========
const scrollTopBtn = document.getElementById('scrollTop');
if (scrollTopBtn) {
  scrollTopBtn.addEventListener('click', () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  });

  let stTicking = false;
  window.addEventListener('scroll', () => {
    if (!stTicking) {
      requestAnimationFrame(() => {
        scrollTopBtn.classList.toggle('is-visible', window.scrollY > 300);
        stTicking = false;
      });
      stTicking = true;
    }
  });
}

// ========== SMOOTH PARALLAX ON HERO ==========
const hero = document.querySelector('.hero');
const heroEst = document.querySelector('.hero-est');

if (hero && heroEst) {
  let ticking = false;
  window.addEventListener('scroll', () => {
    if (!ticking) {
      requestAnimationFrame(() => {
        const scrollY = window.scrollY;
        const heroHeight = hero.offsetHeight;
        if (scrollY < heroHeight) {
          const progress = scrollY / heroHeight;
          heroEst.style.transform = `translateY(calc(-50% + ${scrollY * 0.3}px))`;
          heroEst.style.opacity = 1 - progress * 1.5;
        }
        ticking = false;
      });
      ticking = true;
    }
  });
}

/* THEMELI — Timeline navigation */

// ========== TIMELINE NAV ==========
const timelineNav = document.getElementById('timelineNav');
if (timelineNav) {
  const navButtons = timelineNav.querySelectorAll('.timeline-nav-year');
  const progressBar = document.getElementById('timelineNavProgress');

  // Click to scroll
  navButtons.forEach(btn => {
    btn.addEventListener('click', () => {
      const targetId = btn.getAttribute('data-target');
      const target = document.getElementById(targetId);
      if (target) {
        const offset = 120;
        const top = target.getBoundingClientRect().top + window.scrollY - offset;
        window.scrollTo({ top, behavior: 'smooth' });
      }
    });
  });

  // Track active era on scroll
  const eraIds = Array.from(navButtons).map(btn => btn.getAttribute('data-target'));
  const eraElements = eraIds.map(id => document.getElementById(id)).filter(Boolean);

  function updateActiveYear() {
    const scrollY = window.scrollY + 200;
    let activeIndex = 0;

    eraElements.forEach((el, i) => {
      if (el.offsetTop <= scrollY) {
        activeIndex = i;
      }
    });

    navButtons.forEach((btn, i) => {
      btn.classList.toggle('is-active', i === activeIndex);
    });

    // Update progress bar
    if (progressBar && navButtons.length > 1) {
      const pct = (activeIndex / (navButtons.length - 1)) * 100;
      progressBar.style.width = pct + '%';
    }
  }

  let navTicking = false;
  window.addEventListener('scroll', () => {
    if (!navTicking) {
      requestAnimationFrame(() => {
        updateActiveYear();
        navTicking = false;
      });
      navTicking = true;
    }
  });

  updateActiveYear();
}

/* THEMELI — Project data rendering */

// ========== PROJECTS: DATA-DRIVEN RENDERING ==========
const projGridView = document.getElementById('projGridView');
const projListView = document.getElementById('projListView');
const projMapView = document.getElementById('projMapView');
const mapInner = document.getElementById('mapInner');

// Load projects from Supabase (async) with PROJECTS fallback
if (projGridView) {
(async function renderProjects() {
const projectData = await fetchProjects();
if (!projectData.length) return;
  // Escape HTML entities
  function esc(str) {
    const d = document.createElement('div');
    d.textContent = str;
    return d.innerHTML;
  }

  // Render grid cards
  projectData.forEach(p => {
    const imgStyle = p.image ? ` style="background-image:url('${esc(p.image)}')"` : '';
    projGridView.insertAdjacentHTML('beforeend',
      `<a class="proj-card" data-typology="${esc(p.typology)}" href="project.html#${p.id}">
        <div class="proj-card-img"${imgStyle}></div>
        <div class="proj-card-info"><span class="proj-card-name">${esc(p.name)}</span><span class="proj-card-year">${p.year}</span></div>
        <span class="proj-card-tag">${esc(p.typology)}</span>
      </a>`
    );
  });

  // Render list rows
  if (projListView) {
    projectData.forEach(p => {
      projListView.insertAdjacentHTML('beforeend',
        `<a class="proj-row" data-typology="${esc(p.typology)}" href="project.html#${p.id}"><span class="proj-col proj-col-name">${esc(p.name)}</span><span class="proj-col proj-col-type">${esc(p.typology)}</span><span class="proj-col proj-col-loc">${esc(p.location)}</span><span class="proj-col proj-col-year">${p.year}</span></a>`
      );
    });
  }

  // Render map dots with tooltip cards
  if (mapInner) {
    projectData.forEach(p => {
      if (p.mapX == null || p.mapY == null) return;
      const tooltipImg = p.image ? ` style="background-image:url('${esc(p.image)}')"` : '';
      mapInner.insertAdjacentHTML('beforeend',
        `<a class="proj-map-dot" style="left:${p.mapX}%;top:${p.mapY}%" data-typology="${esc(p.typology)}" href="project.html#${p.id}">
          <div class="proj-map-tooltip">
            <div class="proj-map-tooltip-img"${tooltipImg}></div>
            <div class="proj-map-tooltip-body">
              <span class="proj-map-tooltip-name">${esc(p.name)}</span>
              <span class="proj-map-tooltip-year">${p.year}</span>
            </div>
            <span class="proj-map-tooltip-tag">${esc(p.typology)}</span>
          </div>
        </a>`
      );
    });
  }

  // Update initial count
  const projCount = document.getElementById('projCount');
  if (projCount) {
    projCount.textContent = projectData.length + ' ' + (projectData.length !== 1 ? T.projects : T.project);
  }
})();
}

/* THEMELI — Projects view switching, map, filter */

// ========== PROJECTS VIEW SWITCHING ==========
const projViewToggles = document.getElementById('projViewToggles');

if (projViewToggles && projGridView) {
  const viewBtns = projViewToggles.querySelectorAll('.proj-view-btn');
  const views = { grid: projGridView, list: projListView, map: projMapView };

  viewBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      const target = btn.getAttribute('data-view');
      viewBtns.forEach(b => b.classList.remove('is-active'));
      btn.classList.add('is-active');
      Object.entries(views).forEach(([key, el]) => {
        if (el) el.style.display = key === target ? '' : 'none';
      });
    });
  });
}

// ========== MAP ZOOM & PAN ==========
const mapViewport = document.getElementById('mapViewport');
const mapZoomIn = document.getElementById('mapZoomIn');
const mapZoomOut = document.getElementById('mapZoomOut');

if (mapViewport && mapInner) {
  let scale = 1;
  let panX = 0;
  let panY = 0;
  let isDragging = false;
  let startX = 0;
  let startY = 0;

  function applyTransform(smooth) {
    mapInner.style.transition = smooth ? 'transform 0.4s cubic-bezier(0.25,0.46,0.45,0.94)' : 'none';
    mapInner.style.transform = `translate(${panX}px, ${panY}px) scale(${scale})`;
    mapViewport.classList.toggle('is-zoomed', scale > 1);
  }

  function clampPan() {
    if (scale <= 1) { panX = 0; panY = 0; return; }
    const rect = mapViewport.getBoundingClientRect();
    const maxPan = (rect.width * (scale - 1)) / 2;
    panX = Math.max(-maxPan, Math.min(maxPan, panX));
    panY = Math.max(-maxPan, Math.min(maxPan, panY));
  }

  mapZoomIn.addEventListener('click', () => {
    if (scale < 2) { scale = 2; clampPan(); applyTransform(true); }
  });

  mapZoomOut.addEventListener('click', () => {
    scale = 1; panX = 0; panY = 0; applyTransform(true);
  });

  mapViewport.addEventListener('mousedown', (e) => {
    if (scale <= 1) return;
    isDragging = true;
    startX = e.clientX - panX;
    startY = e.clientY - panY;
    e.preventDefault();
  });

  window.addEventListener('mousemove', (e) => {
    if (!isDragging) return;
    panX = e.clientX - startX;
    panY = e.clientY - startY;
    clampPan();
    applyTransform(false);
  });

  window.addEventListener('mouseup', () => { isDragging = false; });

  mapViewport.addEventListener('touchstart', (e) => {
    if (scale <= 1 || e.touches.length !== 1) return;
    isDragging = true;
    startX = e.touches[0].clientX - panX;
    startY = e.touches[0].clientY - panY;
  }, { passive: true });

  mapViewport.addEventListener('touchmove', (e) => {
    if (!isDragging) return;
    panX = e.touches[0].clientX - startX;
    panY = e.touches[0].clientY - startY;
    clampPan();
    applyTransform(false);
    e.preventDefault();
  }, { passive: false });

  mapViewport.addEventListener('touchend', () => { isDragging = false; });

  mapViewport.addEventListener('dblclick', (e) => {
    if (scale > 1) {
      scale = 1; panX = 0; panY = 0;
    } else {
      scale = 2;
      const rect = mapViewport.getBoundingClientRect();
      panX = -(e.clientX - rect.left - rect.width / 2);
      panY = -(e.clientY - rect.top - rect.height / 2);
      clampPan();
    }
    applyTransform(true);
  });
}

// ========== PROJECTS FILTER (event delegation) ==========
const projFilterToggle = document.getElementById('projFilterToggle');
const projFilters = document.getElementById('projFilters');

if (projFilterToggle && projFilters) {
  projFilterToggle.addEventListener('click', () => {
    projFilters.classList.toggle('is-open');
    projFilterToggle.classList.toggle('is-active');
  });

  projFilters.addEventListener('click', (e) => {
    const btn = e.target.closest('.proj-filter-btn');
    if (!btn) return;

    projFilters.querySelectorAll('.proj-filter-btn').forEach(b => b.classList.remove('is-active'));
    btn.classList.add('is-active');

    const filter = btn.getAttribute('data-filter');
    let visibleCount = 0;

    // Filter all three views using event delegation
    document.querySelectorAll('.proj-row:not(.proj-row-header)').forEach(row => {
      const match = filter === 'all' || row.getAttribute('data-typology') === filter;
      row.classList.toggle('is-hidden', !match);
      if (match) visibleCount++;
    });

    document.querySelectorAll('.proj-card').forEach(card => {
      card.classList.toggle('is-hidden', filter !== 'all' && card.getAttribute('data-typology') !== filter);
    });

    document.querySelectorAll('.proj-map-dot').forEach(dot => {
      dot.classList.toggle('is-hidden', filter !== 'all' && dot.getAttribute('data-typology') !== filter);
    });

    const projCount = document.getElementById('projCount');
    if (projCount) {
      projCount.textContent = visibleCount + ' ' + (visibleCount !== 1 ? T.projects : T.project);
    }
  });
}

/* THEMELI — Subsidiaries detail & lightbox */

// ========== SUBSIDIARIES REACTIVE DETAIL ==========
const subsData = T.subsData;

const subsGrid = document.getElementById('subsGrid');
const subDetail = document.getElementById('subDetail');
const subBack = document.getElementById('subBack');
const subName = document.getElementById('subName');
const subSubtitle = document.getElementById('subSubtitle');
const subDesc = document.getElementById('subDesc');
const subLogo = document.getElementById('subLogo');

if (subsGrid && subDetail) {

  // Gallery lightbox function
  const openGallery = (images, startIndex) => {
    let idx = startIndex || 0;
    const lb = document.createElement('div');
    lb.className = 'lightbox';
    lb.innerHTML = `
      <button class="lightbox-close" aria-label="Close">&times;</button>
      <button class="lightbox-arrow lightbox-prev" aria-label="Previous">&lsaquo;</button>
      <img class="lightbox-img" src="${images[idx]}" alt="">
      <button class="lightbox-arrow lightbox-next" aria-label="Next">&rsaquo;</button>
      <div class="lightbox-counter">${idx + 1} / ${images.length}</div>`;
    document.body.appendChild(lb);

    const img = lb.querySelector('.lightbox-img');
    const counter = lb.querySelector('.lightbox-counter');
    const updateArrows = () => {
      lb.querySelector('.lightbox-prev').style.visibility = images.length > 1 ? 'visible' : 'hidden';
      lb.querySelector('.lightbox-next').style.visibility = images.length > 1 ? 'visible' : 'hidden';
    };
    const show = () => {
      img.src = images[idx];
      counter.textContent = (idx + 1) + ' / ' + images.length;
    };
    updateArrows();

    requestAnimationFrame(() => {
      requestAnimationFrame(() => lb.classList.add('is-visible'));
    });

    const close = () => {
      lb.classList.remove('is-visible');
      setTimeout(() => lb.remove(), 300);
    };
    lb.querySelector('.lightbox-close').addEventListener('click', close);
    lb.querySelector('.lightbox-prev').addEventListener('click', (e) => {
      e.stopPropagation();
      idx = (idx - 1 + images.length) % images.length;
      show();
    });
    lb.querySelector('.lightbox-next').addEventListener('click', (e) => {
      e.stopPropagation();
      idx = (idx + 1) % images.length;
      show();
    });
    lb.addEventListener('click', e => { if (e.target === lb) close(); });
    document.addEventListener('keydown', function handler(e) {
      if (e.key === 'Escape') { close(); document.removeEventListener('keydown', handler); }
      if (e.key === 'ArrowLeft') { idx = (idx - 1 + images.length) % images.length; show(); }
      if (e.key === 'ArrowRight') { idx = (idx + 1) % images.length; show(); }
    });
  };

  // Show subsidiary detail view
  function showSubDetail(key, pushHistory) {
    const data = subsData[key];
    if (!data) return;

    subName.textContent = data.name;
    subSubtitle.textContent = data.subtitle;
    subDesc.innerHTML = data.desc;
    subLogo.setAttribute('data-sub', key);
    subLogo.innerHTML = `<img src="${data.logo}" alt="${data.name}">`;

    // Populate featured grid
    const subFeatured = document.getElementById('subFeatured');
    if (subFeatured) {
      const renderCard = (f) => {
        const hasImg = f.img && f.img !== '';
        const imgTag = hasImg
          ? `<img class="sub-featured-img" src="${f.img}" alt="${f.name}" loading="lazy">`
          : `<div class="sub-featured-img sub-featured-img--empty"></div>`;
        return `<div class="sub-featured-card"${hasImg ? ` data-lightbox="${f.img}"` : ''}>
          ${imgTag}
          <div class="sub-featured-info">
            <span class="sub-featured-name">${f.name}</span>
          </div>
        </div>`;
      };

      if (data.featuredGroups && data.featuredGroups.length) {
        subFeatured.innerHTML = data.featuredGroups.map((group, i) => {
          const divider = i > 0 ? '<div class="sub-featured-divider"></div>' : '';
          return `${divider}<div class="sub-featured-group">
            <div class="sub-featured-group-header">
              <h3 class="sub-featured-group-title">${group.title}</h3>
              <span class="sub-featured-group-subtitle">${group.subtitle}</span>
            </div>
            <div class="sub-featured-group-cards">
              ${group.items.map(renderCard).join('')}
            </div>
          </div>`;
        }).join('');
        subFeatured.classList.add('sub-featured-grid--grouped');
        subFeatured.classList.remove('sub-featured-grid');
      } else if (data.featured && data.featured.length) {
        subFeatured.innerHTML = data.featured.map(renderCard).join('');
        subFeatured.classList.add('sub-featured-grid');
        subFeatured.classList.remove('sub-featured-grid--grouped');
      } else {
        subFeatured.innerHTML = '';
        subFeatured.classList.remove('sub-featured-grid', 'sub-featured-grid--grouped');
      }

      // Attach lightbox to grouped cards (with gallery)
      if (data.featuredGroups) {
        data.featuredGroups.forEach((group, gi) => {
          const gallery = group.gallery || group.items.filter(f => f.img).map(f => f.img);
          const groupEl = subFeatured.querySelectorAll('.sub-featured-group')[gi];
          if (groupEl) {
            groupEl.querySelectorAll('[data-lightbox]').forEach(card => {
              card.addEventListener('click', () => {
                const src = card.getAttribute('data-lightbox');
                const startIdx = gallery.indexOf(src);
                openGallery(gallery, startIdx >= 0 ? startIdx : 0);
              });
            });
          }
        });
      }

      // Attach lightbox to simple featured cards
      if (data.featured) {
        const allImgs = data.featured.filter(f => f.img).map(f => f.img);
        subFeatured.querySelectorAll('[data-lightbox]').forEach(card => {
          card.addEventListener('click', () => {
            const src = card.getAttribute('data-lightbox');
            const startIdx = allImgs.indexOf(src);
            openGallery(allImgs, startIdx >= 0 ? startIdx : 0);
          });
        });
      }
    }

    // Transition: hide grid, show detail
    subsGrid.classList.add('is-hidden');
    subDetail.classList.add('is-active');
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        subDetail.classList.add('is-visible');
      });
    });

    window.scrollTo({ top: 0, behavior: 'smooth' });

    // Update URL hash
    if (pushHistory) {
      window.history.pushState({ sub: key }, '', '#' + key);
    }
  }

  // Show logo grid
  function showSubGrid() {
    subDetail.classList.remove('is-visible');
    setTimeout(() => {
      subDetail.classList.remove('is-active');
      subsGrid.classList.remove('is-hidden');
    }, 400);
  }

  // Click on a subsidiary logo
  document.querySelectorAll('[data-sub]').forEach(el => {
    el.addEventListener('click', () => {
      const key = el.getAttribute('data-sub');
      showSubDetail(key, true);
    });
  });

  // Back button
  if (subBack) {
    subBack.addEventListener('click', () => {
      window.history.back();
    });
  }

  // Handle browser back/forward
  window.addEventListener('popstate', () => {
    const hash = window.location.hash.slice(1);
    if (hash && subsData[hash]) {
      showSubDetail(hash, false);
    } else {
      showSubGrid();
    }
  });

  // Handle initial load with hash
  if (window.location.hash) {
    const key = window.location.hash.slice(1);
    if (subsData[key]) {
      showSubDetail(key, false);
    }
  }
}

/* THEMELI — Project detail page */

// ========== PROJECT DETAIL PAGE ==========
const pdetDetail = document.getElementById('projectDetail');

if (pdetDetail) {
  // Support both ?id=X (direct) and #X (clean URL fallback)
  const params = new URLSearchParams(window.location.search);
  const projectId = parseInt(params.get('id'), 10) || parseInt(window.location.hash.replace('#', ''), 10);

  // Sanitise a string for use inside a CSS url()
  function cssUrl(str) {
    return str ? str.replace(/['"\\()]/g, '\\$&') : '';
  }

  // Load data from Supabase (async)
  (async function() {
  const allProjects = await fetchProjects();
  const currentIdx = allProjects.findIndex(p => Number(p.id) === projectId);
  const project = currentIdx !== -1 ? allProjects[currentIdx] : null;

  if (project) {
    // Set page title
    document.title = `THEMELI — ${project.name}`;

    // Hero image
    const heroImg = document.getElementById('pdetHeroImg');
    if (project.image) {
      heroImg.style.backgroundImage = `url('${cssUrl(project.image)}')`;
      heroImg.classList.add('has-image');
    }

    // Content
    document.getElementById('pdetTag').textContent = project.typology;
    document.getElementById('pdetTitle').textContent = project.name;
    document.getElementById('pdetYear').textContent = project.year;
    document.getElementById('pdetLocation').textContent = project.location || '—';
    document.getElementById('pdetTypology').textContent = project.typology;
    document.getElementById('pdetDesc').textContent = project.description || '';

    // Info board
    const archEl = document.getElementById('pdetArchitect');
    const sizeEl = document.getElementById('pdetSize');
    const statusEl = document.getElementById('pdetStatus');
    const dateCompEl = document.getElementById('pdetDateCompleted');
    const infoLocEl = document.getElementById('pdetInfoLocation');
    const infoTypEl = document.getElementById('pdetInfoTypology');

    archEl.textContent = project.architect || '—';
    sizeEl.textContent = project.size || '—';
    statusEl.textContent = project.status || 'Completed';
    dateCompEl.textContent = project.dateCompleted || String(project.year);
    infoLocEl.textContent = project.location || '—';
    infoTypEl.textContent = project.typology;

    // Hide empty optional rows
    if (!project.architect) document.getElementById('pdetInfoArchitect').style.display = 'none';
    if (!project.size) document.getElementById('pdetInfoSize').style.display = 'none';

    // Related projects — same typology, excluding current
    const related = allProjects
      .filter(p => p.typology === project.typology && p.id !== project.id)
      .slice(0, 4);

    const relatedGrid = document.getElementById('pdetRelatedGrid');
    const relatedSection = document.getElementById('pdetRelated');

    if (related.length > 0 && relatedGrid) {
      related.forEach(p => {
        const imgStyle = p.image ? `background-image:url('${cssUrl(p.image)}')` : '';
        relatedGrid.insertAdjacentHTML('beforeend',
          `<a class="pdet-related-card" href="project.html#${p.id}">
            <div class="pdet-related-card-img" style="${imgStyle}"></div>
            <div class="pdet-related-card-body">
              <span class="pdet-related-card-name">${p.name}</span>
              <span class="pdet-related-card-meta">${p.typology} &middot; ${p.location || ''}</span>
            </div>
          </a>`
        );
      });
    } else if (relatedSection) {
      relatedSection.style.display = 'none';
    }

    // Adjacent project navigation (loops around)
    const prevProject = allProjects[(currentIdx - 1 + allProjects.length) % allProjects.length];
    const nextProject = allProjects[(currentIdx + 1) % allProjects.length];

    const prevLink = document.getElementById('pdetPrev');
    const nextLink = document.getElementById('pdetNext');
    const prevName = document.getElementById('pdetPrevName');
    const nextName = document.getElementById('pdetNextName');

    prevLink.href = `project.html#${prevProject.id}`;
    prevName.textContent = prevProject.name;

    nextLink.href = `project.html#${nextProject.id}`;
    nextName.textContent = nextProject.name;

    // Staggered reveal animation
    requestAnimationFrame(() => {
      pdetDetail.classList.add('is-loaded');
    });
  } else {
    // Project not found — redirect back
    window.location.href = 'projects.html';
  }
  })();
}

/* THEMELI — Email & phone popups */

// ========== EMAIL POPUP ==========
document.querySelectorAll('.email-trigger').forEach(trigger => {
  trigger.addEventListener('click', (e) => {
    e.preventDefault();
    const wrapper = trigger.closest('.email-wrapper');
    // Close any other open popups
    document.querySelectorAll('.email-wrapper.active, .phone-wrapper.active').forEach(w => {
      if (w !== wrapper) w.classList.remove('active');
    });
    wrapper.classList.toggle('active');
  });
});

document.querySelectorAll('.email-copy').forEach(btn => {
  btn.addEventListener('click', () => {
    const email = btn.dataset.email;
    navigator.clipboard.writeText(email).then(() => {
      btn.textContent = T.copied;
      btn.classList.add('copied');
      setTimeout(() => {
        btn.textContent = T.copyAddress;
        btn.classList.remove('copied');
        btn.closest('.email-wrapper').classList.remove('active');
      }, 1500);
    });
  });
});

// ========== PHONE POPUP ==========
document.querySelectorAll('.phone-trigger').forEach(trigger => {
  trigger.addEventListener('click', (e) => {
    e.preventDefault();
    const wrapper = trigger.closest('.phone-wrapper');
    document.querySelectorAll('.phone-wrapper.active, .email-wrapper.active').forEach(w => {
      if (w !== wrapper) w.classList.remove('active');
    });
    wrapper.classList.toggle('active');
  });
});

document.querySelectorAll('.phone-copy').forEach(btn => {
  btn.addEventListener('click', () => {
    const phone = btn.dataset.phone;
    navigator.clipboard.writeText(phone).then(() => {
      btn.textContent = T.copied;
      btn.classList.add('copied');
      setTimeout(() => {
        btn.textContent = T.copyNumber;
        btn.classList.remove('copied');
        btn.closest('.phone-wrapper').classList.remove('active');
      }, 1500);
    });
  });
});

// Close popups when clicking outside
document.addEventListener('click', (e) => {
  if (!e.target.closest('.email-wrapper') && !e.target.closest('.phone-wrapper')) {
    document.querySelectorAll('.email-wrapper.active, .phone-wrapper.active').forEach(w => {
      w.classList.remove('active');
    });
  }
});
