<?php
// Regenerate the static projects-data.js consumed by the public site.
// Only "Public" projects are included. Image URLs are emitted as
// relative paths (/uploads/projects/<legacy_id>/<filename>) so the site
// works on any domain without rebuild.

require __DIR__ . '/common.php';
require_admin();

if (method() !== 'POST') json_err('Method not allowed', 405);

$rows = db()->query("
    SELECT legacy_id, name, name_en, description, description_en,
           year, year_start, typology, location, region, architect, size,
           status, date_completed, client, contractor, participation,
           budget, hero_image, gallery, lat, lng, map_points
    FROM projects
    WHERE visibility = 'Public'
    ORDER BY legacy_id ASC
")->fetchAll();

$out = [];
foreach ($rows as $r) {
    $legacy   = (int)$r['legacy_id'];
    $hero     = (string)($r['hero_image'] ?? '');
    $gallery  = json_decode_safe($r['gallery'], []);
    $points   = json_decode_safe($r['map_points'], null);

    $heroUrl = $hero !== ''
        ? '/uploads/projects/' . $legacy . '/' . rawurlencode($hero)
        : '';
    $galleryUrls = [];
    foreach ($gallery as $g) {
        if (!is_string($g) || $g === '') continue;
        $galleryUrls[] = '/uploads/projects/' . $legacy . '/' . rawurlencode($g);
    }

    $lat = $r['lat'] !== null ? (float)$r['lat'] : null;
    $lng = $r['lng'] !== null ? (float)$r['lng'] : null;
    if ($lat === 0.0 && $lng === 0.0) { $lat = null; $lng = null; }

    $out[] = [
        'id'              => $legacy,
        'name'            => (string)($r['name']            ?? ''),
        'name_en'         => (string)($r['name_en']         ?? ''),
        'description'     => (string)($r['description']     ?? ''),
        'description_en'  => (string)($r['description_en']  ?? ''),
        'year'            => $r['year']       !== null ? (int)$r['year']       : 0,
        'typology'        => (string)($r['typology']        ?? ''),
        'location'        => (string)($r['location']        ?? ''),
        'region'          => (string)($r['region']          ?? ''),
        'architect'       => (string)($r['architect']       ?? ''),
        'size'            => (string)($r['size']            ?? ''),
        'status'          => (string)($r['status']          ?? 'Completed'),
        'dateCompleted'   => (string)($r['date_completed']  ?? ''),
        'image'           => $heroUrl,
        'images'          => $galleryUrls,
        'lat'             => $lat,
        'lng'             => $lng,
        'points'          => is_array($points) && count($points) >= 2 ? $points : null,
        'client'          => (string)($r['client']          ?? ''),
        'contractor'      => (string)($r['contractor']      ?? ''),
        'participation'   => (string)($r['participation']   ?? ''),
        'yearStart'       => $r['year_start'] !== null ? (int)$r['year_start'] : null,
        'budget'          => $r['budget']     !== null ? (float)$r['budget']   : null,
    ];
}

$json = json_encode($out, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
$body = "/**\n * THEMELI — Projects Data\n * Generated by /api/publish.php — do not edit by hand.\n */\nconst PROJECTS = " . $json . ";\n";

if (@file_put_contents(DATA_FILE, $body) === false) {
    json_err('Could not write ' . DATA_FILE . ' — check filesystem permissions', 500);
}

json_ok([
    'count'   => count($out),
    'written' => DATA_FILE,
]);
