/* THEMELI — Internationalization data */

// UI strings (non-content translations)
const I18N = {
  en: {
    projects: 'Projects', project: 'Project',
    copied: 'Copied!', copyAddress: 'Copy Address', copyNumber: 'Copy Number',
    clearAll: 'Clear All',
    typ: {}
  },
  el: {
    projects: 'Έργα', project: 'Έργο',
    copied: 'Αντιγράφηκε!', copyAddress: 'Αντιγραφή Διεύθυνσης', copyNumber: 'Αντιγραφή Αριθμού',
    clearAll: 'Καθαρισμός',
    typ: {
      'Buildings': 'Κτίρια',
      'Railways': 'Σιδηρόδρομοι',
      'Roadworks': 'Οδοποιία',
      'Tunnels': 'Σήραγγες',
      'Industrial & Energy': 'Βιομηχανικά & Ενέργεια',
      'Utility Networks': 'Δίκτυα Κοινής Ωφέλειας',
      'Dams': 'Φράγματα',
      'Ports & Marine': 'Λιμάνια & Θαλάσσια',
      'Urban Redevelopment': 'Αστική Ανάπλαση'
    }
  }
};
const T = I18N[LANG];

// Subsidiary data loaded from external subsidiaries-data.js (generated by build)
// Prepend BASE to all asset paths at runtime
function prefixSubsPaths(data) {
  if (!data || !BASE) return data;
  const result = {};
  for (const [key, sub] of Object.entries(data)) {
    const s = JSON.parse(JSON.stringify(sub)); // deep clone
    if (s.logo) s.logo = BASE + s.logo;
    if (s.featured) {
      s.featured.forEach(f => { if (f.img) f.img = BASE + f.img; });
    }
    if (s.featuredGroups) {
      s.featuredGroups.forEach(g => {
        if (g.items) g.items.forEach(f => { if (f.img) f.img = BASE + f.img; });
        if (g.gallery) g.gallery = g.gallery.map(p => BASE + p);
      });
    }
    result[key] = s;
  }
  return result;
}

// Attach subsData to T for backward compatibility with subsidiaries page
const rawSubsData = (typeof SUBS_DATA !== 'undefined') ? SUBS_DATA[LANG] : {};
T.subsData = prefixSubsPaths(rawSubsData);

