/* THEMELI — Internationalization (strings come from i18n-data.js, generated by build.js) */

// Flatten the per-language block into the shape the rest of the app expects.
// ui.* is promoted to the top level; typology→typ, status→stat, location→loc
// are kept under their legacy short names to avoid churn in consumers.
function _flattenStrings(lang) {
  var src = (typeof I18N_STRINGS !== 'undefined' && I18N_STRINGS[lang]) || {};
  var out = {};
  if (src.ui) for (var k in src.ui) out[k] = src.ui[k];
  out.typ  = src.typology || {};
  out.stat = src.status || {};
  out.loc  = src.location || {};
  out.inquiryType = src.inquiryType || {};
  return out;
}

const I18N = {
  en: _flattenStrings('en'),
  el: _flattenStrings('el'),
};
const T = I18N[LANG];

// Subsidiary data loaded from external subsidiaries-data.js (generated by build)
// Prepend BASE to all asset paths at runtime
function prefixSubsPaths(data) {
  if (!data || !BASE) return data;
  const result = {};
  for (const [key, sub] of Object.entries(data)) {
    const s = JSON.parse(JSON.stringify(sub)); // deep clone
    if (s.logo) s.logo = BASE + s.logo;
    if (s.featured) {
      s.featured.forEach(f => { if (f.img) f.img = BASE + f.img; });
    }
    if (s.featuredGroups) {
      s.featuredGroups.forEach(g => {
        if (g.items) g.items.forEach(f => { if (f.img) f.img = BASE + f.img; });
        if (g.gallery) g.gallery = g.gallery.map(p => BASE + p);
      });
    }
    result[key] = s;
  }
  return result;
}

const rawSubsData = (typeof SUBS_DATA !== 'undefined') ? SUBS_DATA[LANG] : {};
T.subsData = prefixSubsPaths(rawSubsData);

// Preserve query string (e.g. ?id=42) when switching language so deep-linked
// pages like /en/project?id=42 don't lose context.
(function preserveQueryOnLangSwitch() {
  const search = window.location.search;
  if (!search) return;
  document.querySelectorAll('[data-lang-switch]').forEach(a => {
    try {
      const u = new URL(a.getAttribute('href'), window.location.href);
      u.search = search;
      a.setAttribute('href', u.pathname + u.search);
    } catch (_) { /* ignore malformed href */ }
  });
})();
