/**
 * THEMELI — Projects Data
 * Edit via admin panel or directly in this file.
 */
const PROJECTS = [
  {
    id: 1,
    name: "Νοσοκομείο Χαλκίδος",
    name_en: "",
    description: "Ανέγερση νέου κτιρίου του γενικού νοσοκομείου Χαλκίδος",
    description_en: "",
    year: 1974,
    typology: "Buildings",
    location: "Κως",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "Δ/ΝΣΗ ΤΕΧΝΙΚΩΝ ΥΠΗΡΕΣΙΩΝ ΝΑ ΧΑΛΚΙΔΑΣ",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: null,
    budget: 289571.1519
  },
  {
    id: 2,
    name: "Κέντρων διανομής 150 ΚΥ Αριστείδου και Πειραιώς της Δ.Ε.Η",
    name_en: "",
    description: "Κατασκευή των κέντρων διανομής 150 ΚΥ Αριστείδου και Πειραιώς της Δ.Ε.Η.",
    description_en: "",
    year: 1980,
    typology: "Buildings",
    location: "Πειραιάς",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΣΗΜΕΝΣ ΕΛΛΑΣ Α.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1973,
    budget: 1106634.603
  },
  {
    id: 3,
    name: "Διαμόρφωση εκβολ. Κηφισού",
    name_en: "",
    description: "Διαμόρφωση εκβολ. Κηφισού (εργολαβία ΦΕΕΚ)",
    description_en: "",
    year: 1978,
    typology: "Utility Networks",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1978,
    budget: 19075.57
  },
  {
    id: 4,
    name: "Ρέμμα Φιλοθέης",
    name_en: "",
    description: "Διευθέτηση ρέμματος Φιλοθέης (εργολαβία Ρ2)",
    description_en: "",
    year: 1978,
    typology: "Utility Networks",
    location: "Φιλοθέη",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1978,
    budget: 1161012.47
  },
  {
    id: 5,
    name: "Συλλεκτήρες Ανατ. Συν. Πρωτεύουσας",
    name_en: "",
    description: "Συλλεκτήρες Ανατ. Συν. Πρωτεύουσας (εργολαβία Μ4)",
    description_en: "",
    year: 1978,
    typology: "Utility Networks",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1978,
    budget: 63327.95
  },
  {
    id: 6,
    name: "Συλλεκτήρες Ανατ. Συν/σμών και αντιπλημμυρικά έργα Χαλανδρίου",
    name_en: "",
    description: "Συλλεκτήρες Ανατ. Συν/σμών και αντιπλημμυρικά έργα Χαλανδρίου (εργολαβία Μ14)",
    description_en: "",
    year: 1978,
    typology: "Utility Networks",
    location: "Χαλανδρί",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1978,
    budget: 287086.72
  },
  {
    id: 7,
    name: "Συλλεκτήρες ομβρίων Δυτ. Συν. Πρωτεύουσας",
    name_en: "",
    description: "Συλλεκτήρες ομβρίων Δυτ. Συν. Πρωτεύουσας (εργολαβία Β1)",
    description_en: "",
    year: 1978,
    typology: "Utility Networks",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1978,
    budget: 94991.93
  },
  {
    id: 8,
    name: "Συλλεκτήρες ομβρίων Ιεράς οδού",
    name_en: "",
    description: "Συλλεκτήρες ομβρίων Ιεράς οδού (εργολαβία Ρ4)",
    description_en: "",
    year: 1978,
    typology: "Utility Networks",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1978,
    budget: 259646.37
  },
  {
    id: 9,
    name: "Ρέμμα Ποδονίφτη",
    name_en: "",
    description: "Διευθέτηση ρέμματος Ποδονίφτη (εργολαβία Ρ13)",
    description_en: "",
    year: 1979,
    typology: "Utility Networks",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1979,
    budget: 908369.19
  },
  {
    id: 10,
    name: "Συλλεκτήρες Ανατ. Συν/σμών και αντιπλημμυρικά έργα Χαλανδρίου",
    name_en: "",
    description: "Συλλεκτήρες Ανατ. Συν/σμών και αντιπλημμυρικά έργα Χαλανδρίου (εργολαβία Μ7)",
    description_en: "",
    year: 1979,
    typology: "Utility Networks",
    location: "Χαλανδρί",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1979,
    budget: 1767683.05
  },
  {
    id: 11,
    name: "Φρεατίων Υδροσυλλογής",
    name_en: "",
    description: "Κατασκευή φρεατίων Υδροσυλλογής (εργολαβία Μ24)",
    description_en: "",
    year: 1980,
    typology: "Utility Networks",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1980,
    budget: 86791.99
  },
  {
    id: 12,
    name: "1ου Δ.Σ. Γαλατσίου Αττικής",
    name_en: "",
    description: "Κατασκευή 1ου Δ.Σ. Γαλατσίου Αττικής",
    description_en: "",
    year: 1985,
    typology: "Buildings",
    location: "Κως",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΟΡΓΑΝΙΣΜΟΣ ΣΧΟΛΙΚΩΝ ΚΤΙΡΙΩΝ",
    contractor: "Κ/ΞΙΑ Κ. ΚΟΡΟΔΗΜΑΣ - Δ. ΝΤΙΝΟΠΟΥΛΟΣ",
    participation: "",
    yearStart: 1983,
    budget: 35639.03155
  },
  {
    id: 13,
    name: "Τμήματα Μεστής - Μάκρης και Μαιστρου",
    name_en: "",
    description: "Τμήματα \"Μεστής - Μάκρης\" και \"Μαιστρου - Λουτρών) της εθνικηςοδού Θεσσαλονίκης - συνόρων με την Τουρκία)",
    description_en: "",
    year: 1987,
    typology: "Roadworks",
    location: "Θεσσαλονίκη",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΠΕΡΙΦΕΡΕΙΑ ΑΝΑΤΟΛΙΚΗΣ ΜΑΚΕΔΟΝΙΑΣ - ΘΡΑΚΗΣ",
    contractor: "ΕΛΛΗΝΙΚΑ ΤΕΧΝΙΚΑ ΕΡΓΑ Α.Ε. (νυν ΘΕΜΕΛΗ Α.Ε.)",
    participation: "100%",
    yearStart: 1983,
    budget: 1609502.5
  },
  {
    id: 14,
    name: "Αντιπλημμυρικά Έργα στους δήμους Παλαιού Φαλήρου και Αλίμου",
    name_en: "",
    description: "Κατασκευή αντιπλημμυρικά έργων στους δήμους Παλαιού Φαλήρου και Αλίμου (εργολαβία Β19)",
    description_en: "",
    year: 1984,
    typology: "Utility Networks",
    location: "Παλαιό Φάληρο",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΔΗΜΗΤΡΙΟΣ ΝΤΙΝΟΠΟΥΛΟΣ ΕΔΕ",
    participation: "100%",
    yearStart: 1983,
    budget: 264845.46
  },
  {
    id: 15,
    name: "Μεταξύ χλμ 327-329 της γραμμής Δομοκού - Λάρισας",
    name_en: "",
    description: "Κατασκευή χωματουργικών και τεχνικών έργων μεταξύ χλμ 327-329 της γραμμής Δομοκού - Λάρισας",
    description_en: "",
    year: 1988,
    typology: "Railways",
    location: "Δομοκός",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΟΣΕ Α.Ε.",
    contractor: "ΕΛΛΗΝΙΚΑ ΤΕΧΝΙΚΑ ΕΡΓΑ Α.Ε. (νυν ΘΕΜΕΛΗ Α.Ε.)",
    participation: "100%",
    yearStart: 1984,
    budget: 1602347.762
  },
  {
    id: 16,
    name: "Νέες υπόγειες εγκαταστάσεις Σ.Δ.Α.Μ",
    name_en: "",
    description: "Νέες υπόγειες εγκαταστάσεις Σ.Δ.Α.Μ.",
    description_en: "",
    year: 1989,
    typology: "Tunnels",
    location: "",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΕΘΝΙΚΗ ΑΜΥΝΑΣ (Γ4)",
    contractor: "ΕΛΛΗΝΙΚΑ ΤΕΧΝΙΚΑ ΕΡΓΑ Α.Ε. (νυν ΘΕΜΕΛΗ Α.Ε.)",
    participation: "100%",
    yearStart: 1984,
    budget: 2911743.138
  },
  {
    id: 17,
    name: "Νοσοκομείο 100 κλινών",
    name_en: "",
    description: "Οικοδομικές εργασίες κτιρίων και Περιβάλλοντος χώρουνέου κτιριακού συγκροτήματος νοσοκομείου 100 κλινών",
    description_en: "",
    year: 1988,
    typology: "Buildings",
    location: "Κεφαλλονιά",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΓΕΝΙΚΟ ΝΟΜΑΡΧΙΑΚΟ ΝΟΣΟΚΟΜΕΙΟ ΚΕΦΑΛΛΗΝΙΑΣ",
    contractor: "ΕΛΛΗΝΙΚΑ ΤΕΧΝΙΚΑ ΕΡΓΑ Α.Ε. (νυν ΘΕΜΕΛΗ Α.Ε.)",
    participation: "100%",
    yearStart: 1984,
    budget: 2539787.533
  },
  {
    id: 18,
    name: "Έργα στο Δήμο Ελευσίνας",
    name_en: "",
    description: "Συνέχιση της κατασκευής των αντιπλημμυρικών έργων στο Δήμο Ελευσίνας",
    description_en: "",
    year: 1985,
    typology: "Utility Networks",
    location: "Ελευσίνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕ.ΧΩ.Δ.Ε.",
    contractor: "ΕΛΛΗΝΙΚΑ ΤΕΧΝΙΚΑ ΕΡΓΑ Α.Ε. (νυν ΘΕΜΕΛΗ Α.Ε.)",
    participation: "100%",
    yearStart: 1984,
    budget: 166375.1724
  },
  {
    id: 19,
    name: "Ανακατασκευή Γέφυρα Χαμοστέρνας Θεσσαλονίκης",
    name_en: "",
    description: "Κ02/85: Ανακατασκευή Γέφυρας Χαμοστέρνας Θεσσαλονίκης",
    description_en: "",
    year: 1987,
    typology: "Roadworks",
    location: "Θεσσαλονίκη",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "ΕΛΛΗΝΙΚΑ ΤΕΧΝΙΚΑ ΕΡΓΑ Α.Ε. (νυν ΘΕΜΕΛΗ Α.Ε.)",
    participation: "100%",
    yearStart: 1985,
    budget: 1347539.748
  },
  {
    id: 20,
    name: "Νέο κτίριο θαλάμου ελέγχου",
    name_en: "",
    description: "Νέο κτίριο θαλάμου ελέγχου",
    description_en: "",
    year: 1987,
    typology: "Industrial & Energy",
    location: "",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΛΛΗΝΙΚΑ ΔΙΥΛΙΣΤΗΡΙΑ ΑΣΠΡΟΠΥΡΓΟΥ Α.Ε.",
    contractor: "ΕΛΛΗΝΙΚΑ ΤΕΧΝΙΚΑ ΕΡΓΑ Α.Ε. (νυν ΘΕΜΕΛΗ Α.Ε.)",
    participation: "100%",
    yearStart: 1985,
    budget: 396133.887
  },
  {
    id: 21,
    name: "Οινοποιείο Ρόμπολας",
    name_en: "",
    description: "Οικοδομικές εργασίες & Η/Μ εγκαταστάσεις οινοποιείου Ρόμπολας",
    description_en: "",
    year: 1989,
    typology: "Industrial & Energy",
    location: "Κεφαλλονιά",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΑΓΡΟ/ΒΙΟΜΗΧΑΝΙΚΟΣ ΣΥΝΕΤΑΙΡΙΣΜΟΣ ΠΑΡΑΓΩΓΩΝ ΡΟΜΠΟΛΑΣ",
    contractor: "ΕΛΛΗΝΙΚΑ ΤΕΧΝΙΚΑ ΕΡΓΑ Α.Ε. (νυν ΘΕΜΕΛΗ Α.Ε.)",
    participation: "100%",
    yearStart: 1985,
    budget: 381394.8291
  },
  {
    id: 22,
    name: "Υποκατάστημα Ελευσίνας",
    name_en: "",
    description: "Ανέγερση νέου υποκαταστήματος Ελευσίνας",
    description_en: "",
    year: 1988,
    typology: "Buildings",
    location: "Ελευσίνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΘΝΙΚΗ ΤΡΑΠΕΖΑ ΤΗΣ ΕΛΛΑΔΟΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1986,
    budget: 319187.6537
  },
  {
    id: 23,
    name: "Βορ. Ρέμμα Τραχώνων & κατασκευή αντιπλημμυρικών έργων",
    name_en: "",
    description: "Διευθέτηση τμημ. Βορ. Ρέμματος Τραχώνων & κατασκευή αντιπλημμυρικών έργων στο Δήμο Αργυρούπολης (εργολαβία Β49)",
    description_en: "",
    year: 1989,
    typology: "Utility Networks",
    location: "Αργυρούπολη",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1987,
    budget: 234188.6456
  },
  {
    id: 24,
    name: "Π. Κηφισού κατάντη παραλιακής Λεωφόρου Ποσειδώνος",
    name_en: "",
    description: "Αναδιευθέτηση Π. Κηφισού κατάντη παραλιακής Λεωφόρου Ποσειδώνος",
    description_en: "",
    year: 1991,
    typology: "Railways",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "Κ/Ξ ΑΚΤΩΡ Α.Ε. ΘΕΜΕΛΗ Α.Ε.",
    participation: "12%",
    yearStart: 1988,
    budget: 4130854.43
  },
  {
    id: 25,
    name: "Αποχετευτικά έργα διάθεσης λυμάτων πόλης ΚΩ",
    name_en: "",
    description: "Αποχετευτικά έργα διάθεσης λυμάτων πόλης ΚΩ",
    description_en: "",
    year: 1992,
    typology: "Utility Networks",
    location: "Κως",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΗΜΟΤΙΚΗ ΕΠΙΧΕΙΡΗΣΗ ΥΔΡΕΥΣΗΣ ΑΠΟΧΕΤΕΥΣΗΣ ΚΩ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1988,
    budget: 2121790.169
  },
  {
    id: 26,
    name: "Δίκτυα ομβρίων - ακαθάρτων και ύδρευσης Μυτιλήνης - Περιοχή Γ",
    name_en: "",
    description: "Κατασκευή δικτύων ομβρίων - ακαθάρτων και ύδρευσης κεντρικού και βόρειου τμήματος πόλης Μυτιλήνης - Περιοχή Γ",
    description_en: "",
    year: 2001,
    typology: "Utility Networks",
    location: "Μυτιλήνη",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΥΑ ΜΥΤΙΛΗΝΗΣ",
    contractor: "Κ/Ξ ΕΥΚΛΕΙΔΗΣ ΑΤΕ - ΘΕΜΕΛΗ Α.Ε.",
    participation: "50%",
    yearStart: 1988,
    budget: 9630435.44
  },
  {
    id: 27,
    name: "Σήραγγα Εκτροπής του Φράγματος Μουζακίου στον Πάμισο Ποταμό",
    name_en: "",
    description: "Κατασκευή Σήραγγας Εκτροπής και Συναφών Έργων του Φράγματος Μουζακίου στον Πάμισο Ποταμό",
    description_en: "",
    year: 1990,
    typology: "Tunnels",
    location: "Μουζάκι",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΗ",
    contractor: "Κ/Ξ ΜΗΧΑΝΙΚΗ Α.Ε. -  ΘΕΜΕΛΗ Α.Ε.",
    participation: "37.50%",
    yearStart: 1988,
    budget: 1991344.987
  },
  {
    id: 28,
    name: "Σήραγγα Εκτροπής του Φράγματος πύλης στον Ποταμό Πορταικό",
    name_en: "",
    description: "Κατασκευή Σήραγγας Εκτροπής και Συναφών Έργων του Φράγματος πύλης  στον  Ποταμό  Πορταικό",
    description_en: "",
    year: 1989,
    typology: "Tunnels",
    location: "Τρίκαλα",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΗ",
    contractor: "Κ/Ξ ΜΗΧΑΝΙΚΗ Α.Ε. -  ΘΕΜΕΛΗ Α.Ε.",
    participation: "37.50%",
    yearStart: 1988,
    budget: 1242348.402
  },
  {
    id: 29,
    name: "ΠΘΑ στο Μεταλλικό Κιλκίς",
    name_en: "",
    description: "Κατασκευή ΠΘΑ στο Μεταλλικό Κιλκίς",
    description_en: "",
    year: 1991,
    typology: "Buildings",
    location: "Κιλκίς",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "737 Δνση Στρκων Εργων",
    contractor: "Κ/Ξ ΠΑΡΝΩΝ Α.Ε. - ΘΕΕΜΕΛΗ Α.Ε- ΑΤΕΚ ΑΕ",
    participation: "",
    yearStart: 1989,
    budget: 3653705.062
  },
  {
    id: 30,
    name: "Αποχέτευση ακαθάρτων Δ.Ε.Υ.Α. Ναυπλίου",
    name_en: "",
    description: "Αποχέτευση ακαθάρτων Δ.Ε.Υ.Α. Ναυπλίου - Κατασκευή τμήματος του δικτύου αποχέτευσης Ακαθάρτων της πόλης του Ναυπλίου",
    description_en: "",
    year: 1992,
    typology: "Utility Networks",
    location: "Ναύπλιο",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΥΑ ΝΑΥΠΛΙΟΥ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1990,
    budget: 646162.876
  },
  {
    id: 31,
    name: "Εκσυγχρονισμός του στρατηγείου Comedeast",
    name_en: "",
    description: "Εκσυγχρονισμός του στρατηγείου Comedeast",
    description_en: "",
    year: 1994,
    typology: "Buildings",
    location: "Λάρισα",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΕΘΝΙΚΗΣ ΑΜΥΝΑΣ",
    contractor: "Κ/Ξ ΘΕΜΕΛΗ Α.Ε. - ΓΕΝΕΡ Α.Ε.",
    participation: "50%",
    yearStart: 1990,
    budget: 5966168.097
  },
  {
    id: 32,
    name: "ΠΘΑ στο Σταυροχώρι",
    name_en: "",
    description: "Κατασκευή ΠΘΑ στο Σταυροχώρι",
    description_en: "",
    year: 1993,
    typology: "Buildings",
    location: "Σταυροχώρι",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "737 Δνση Στρκων Εργων",
    contractor: "Κ/Ξ ΠΑΝΤΕΧΝΙΚΗΑ.Ε. -  ΘΕΜΕΛΗ Α.Ε. - Ι. ΣΙΓΑΛΑΣ ΚΑΙ ΣΙΑ Α.Ε.",
    participation: "",
    yearStart: 1990,
    budget: 4147443.836
  },
  {
    id: 33,
    name: "Σήραγγος Ορφανών, Γέφυρα ποταμού Ενιπέα και χωματουργικών και...",
    name_en: "",
    description: "Κατασκευή σήραγγος Ορφανών, γέφυρας ποταμού Ενιπέα και χωματουργικών και λοιπών τεχνικών έργων για την νέα διπλή σιδηροδρομική γραμμή μεταξύ ΧΛΜ 310-319",
    description_en: "",
    year: 1996,
    typology: "Railways",
    location: "Τρίκαλα",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΟΣΕ Α.Ε.",
    contractor: "Κ/Ξ ΘΕΜΕΛΗ Α.Ε. - ΑΚΤΩΡ. Α.Ε",
    participation: "50%",
    yearStart: 1991,
    budget: 11543547.39
  },
  {
    id: 34,
    name: "Για την νέα διπλή σιδηροδρομική γραμμή μεταξύ Σ.Σ. Αιγινίου - ΧΛΜ 473",
    name_en: "",
    description: "Κατασκευή χωματουργικών και τεχνικών έργων για την νέα διπλή σιδηροδρομική γραμμή μεταξύ Σ.Σ. Αιγινίου - ΧΛΜ 473",
    description_en: "",
    year: 1994,
    typology: "Railways",
    location: "",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΟΣΕ Α.Ε.",
    contractor: "Κ/Ξ ΘΕΜΕΛΗ Α.Ε. - ΑΚΤΩΡ. Α.Ε",
    participation: "95%",
    yearStart: 1991,
    budget: 6867406.233
  },
  {
    id: 35,
    name: "Συγκροτηματος Κολλέγιου Αθηνών στο Ψυχικό",
    name_en: "",
    description: "Κατασκευή κλειστού αθλητικού συγκροτηματος Κολλέγιου Αθηνών στο Ψυχικό",
    description_en: "",
    year: 1995,
    typology: "Buildings",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΛΛΗΝΟΑΜΕΡΙΚΑΝΙΚΟΝ ΕΚΠΑΙΔΕΥΤΙΚΟ ΙΔΡΥΜΑ (ΚΟΛΛΕΓΙΟ ΑΘΗΝΩΝ)",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1992,
    budget: 2421129.861
  },
  {
    id: 36,
    name: "Μήθυμνας Ν. Λέσβου",
    name_en: "",
    description: "Κατασκευή Λιμνοδεξαμενής Μήθυμνας Ν. Λέσβου",
    description_en: "",
    year: 1995,
    typology: "Industrial & Energy",
    location: "Λέσβος",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΝΑ ΛΕΣΒΟΥ",
    contractor: "ΚΑΣΤΩΡ Α.Ε. (Σύσταση ΚΞΙΑΣ: Κ/ΞΙΑ ΚΑΣΤΩΡ Α.Ε. -ΘΕΜΕΛΗ ΑΤΤΕ - Φ. ΒΑΣΙΝΙΩΤΗΣ Α. ΧΩΜΕΝΙΔΗΣ ΚΑΙ ΣΙΑ Ε.Ε.)",
    participation: "34%",
    yearStart: 1992,
    budget: 2781950.28
  },
  {
    id: 37,
    name: "Σήραγγα Προσαγωγής και Συναφών Εργων του ΥΗΕ Μεσοχώρας στον ποταμό...",
    name_en: "",
    description: "Κατασκευή σήραγγας Προσαγωγής και Συναφών Εργων του ΥΗΕ Μεσοχώρας στον ποταμό Αχελώο",
    description_en: "",
    year: 1998,
    typology: "Tunnels",
    location: "Μεσοχώρα",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΗ Α.Ε.",
    contractor: "Κ/Ξ ΜΗΧΑΝΙΚΗ Α.Ε. -  ΘΕΜΕΛΗ Α.Ε. - ΠΑΡΝΩΝ Α.Ε.",
    participation: "25%",
    yearStart: 1992,
    budget: 23744858.67
  },
  {
    id: 38,
    name: "Αντιεκκρηκτική προστασία στρατηγείου Comedeast",
    name_en: "",
    description: "Αντιεκκρηκτική προστασία  στρατηγείου Comedeast",
    description_en: "",
    year: 1998,
    typology: "Buildings",
    location: "Λάρισα",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΕΘΝΙΚΗΣ ΑΜΥΝΑΣ",
    contractor: "Κ/Ξ  ΘΕΜΕΛΗ Α.Ε. - ΓΕΝΕΡ Α.Ε.",
    participation: "50%",
    yearStart: 1993,
    budget: 144961.8547
  },
  {
    id: 39,
    name: "Επέκταση Κτίριο υπο/ματος Καλαμάτας",
    name_en: "",
    description: "Αποκατάσταση - επέκταση κτιρίου υπο/ματος Καλαμάτας",
    description_en: "",
    year: 1996,
    typology: "Buildings",
    location: "Καλαμάτα",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΘΝΙΚΗ ΤΡΑΠΕΖΑ ΤΗΣ ΕΛΛΑΔΟΣ",
    contractor: "Κ/Ξ ΘΕΜΕΛΗ Α.Ε. - RODEX O.E.",
    participation: "50%",
    yearStart: 1993,
    budget: 720334.8291
  },
  {
    id: 40,
    name: "Δίκτυα ύδρευσης - αποχέτευσης του οικοδομικού συνεταιρισμού...",
    name_en: "",
    description: "Κατασκευή δικτύων ύδρευσης  - αποχέτευσης  του οικοδομικού συνεταιρισμού Καφεπολών \" Ο ΑΓΙΟΣ ΓΕΩΡΓΙΟΣ\"",
    description_en: "",
    year: 1995,
    typology: "Utility Networks",
    location: "",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΑΣΤΙΚΟΣ ΟΙΚΟΔΟΜΙΚΟΣ ΣΥΝ/ΣΜΟΣ \"Ο ΑΓΙΟΣ ΓΕΩΡΓΙΟΣ\"",
    contractor: "Κ/Ξ ΑΙΟΛΙΚΗ ΤΕΧΝΙΚΗ Α.Ε.- ΘΕΜΕΛΗ Α.Ε.",
    participation: "20%",
    yearStart: 1994,
    budget: 880793.5671
  },
  {
    id: 41,
    name: "Εκτέλεση εργασιών πλήρους κατασκευής του αυτ/μου με τα σύνοδά του...",
    name_en: "",
    description: "Εκτέλεση εργασιών πλήρους κατασκευής του αυτ/μου  με τα σύνοδά του έργα στο τμήμα Παράκαμψης Λάρισας (Ανατολική) από Χ.Θ. 346 + 000 έως Χ.Θ. 368+000",
    description_en: "",
    year: 1999,
    typology: "Buildings",
    location: "Λάρισα",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "Κ/Ξ ΠΑΡΑΚΑΜΨΗ ΛΑΡΙΣΑΣ",
    participation: "6%",
    yearStart: 1995,
    budget: 93186075.55
  },
  {
    id: 42,
    name: "ΜελέΚτίριο γραφείων στην Αλσούπολη Δήμου Ν. Ιωνίας",
    name_en: "",
    description: "Μελέτη και κατασκευή Ιδιόκτητου κτιρίου γραφείων στην Αλσούπολη Δήμου Ν. Ιωνίας",
    description_en: "",
    year: 1995,
    typology: "Buildings",
    location: "Νέα Ιωνία",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1995,
    budget: 8030000.0
  },
  {
    id: 43,
    name: "Νέα διπλή σιδηροδρομική γραμμή Ελευσίνας",
    name_en: "",
    description: "Νέα διπλή σιδηροδρομική γραμμή Ελευσίνας - Κορίνθου, Τμήμα Ισθμός - Κυράς Βρύση",
    description_en: "",
    year: 1999,
    typology: "Railways",
    location: "Ελευσίνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΡΓΑ ΟΣΕ Α.Ε.",
    contractor: "Κ/Ξ ILBAU GmbH - ΘΕΜΕΛΗ Α.Ε. - ΠΟΛΥΤΕΧΝΙΚΗ Α.Ε.",
    participation: "33%",
    yearStart: 1996,
    budget: 11305933.52
  },
  {
    id: 44,
    name: "Τμήμα Κεφαλόβρυσο - Αγγελόκαστρο παράκαμψης Αγρινίου",
    name_en: "",
    description: "Τμήμα Κεφαλόβρυσο - Αγγελόκαστρο παράκαμψης Αγρινίου",
    description_en: "",
    year: 2003,
    typology: "Buildings",
    location: "Αγρίνιο",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "Κ/Ξ ΑΤΕΜΚΕ ΑΤΕ - ΕΥΚΛΕΙΔΗΣ ΑΤΕ - ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1997,
    budget: 40244754.22
  },
  {
    id: 45,
    name: "Δίκτυα όμβριων - ακαθάρτων και ύδρευσης κεντρικού και βορείου...",
    name_en: "",
    description: "Κατασκευή δικτύων όμβριων - ακαθάρτων και ύδρευσης κεντρικού και βορείου τμήματος πόλης Μυτιλήνης - περιοχή Γ’",
    description_en: "",
    year: 2002,
    typology: "Utility Networks",
    location: "Μυτιλήνη",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΥΑΜ",
    contractor: "Κ/Ξ ΕΥΚΛΕΙΔΗΣ Α.Τ.Ε. - ΘΕΜΕΛΗ Α.Ε.",
    participation: "50%",
    yearStart: 1998,
    budget: 6090375.398
  },
  {
    id: 46,
    name: "Αντιπλημμυρική προστασία ευρύτερης περιοχής Αμουρίου -Λιανοκλαδιού...",
    name_en: "",
    description: "Αντιπλημμυρική προστασία ευρύτερης περιοχής Αμουρίου -Λιανοκλαδιού - Ζηλευτού Ν. Φθιώτιδας",
    description_en: "",
    year: 2001,
    typology: "Utility Networks",
    location: "Λαμία",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΓΕΩΡΓΙΑΣ",
    contractor: "Κ/Ξ ΘΕΜΕΛΗ Α.Ε. - ΠΟΛΥΤΕΧΝΙΚΗ Α.Ε.",
    participation: "60%",
    yearStart: 1998,
    budget: 2451564.49
  },
  {
    id: 47,
    name: "Εγνατία Οδός : Τμήμα Δερβένι - Νυμφόπετρα",
    name_en: "",
    description: "Εγνατία Οδός : Τμήμα Δερβένι - Νυμφόπετρα",
    description_en: "",
    year: 2007,
    typology: "Roadworks",
    location: "Θεσσαλονίκη",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΓΝΑΤΙΑ ΟΔΟΣ Α.Ε.",
    contractor: "Κ/Ξ ΕΤΕΠ ΑΕ - ΘΕΜΕΛΗ Α.Ε -ΒΙΟΤΕΡ Α.Ε. - ΤΕΧΝΙΚΗ ΕΝΩΣΙΣ Α.Ε.",
    participation: "25%",
    yearStart: 1998,
    budget: 117543830.94
  },
  {
    id: 48,
    name: "Ολοκλήρωση Διευθέτησης και κάλυψης ρεμματος Μιχελή",
    name_en: "",
    description: "Ολοκλήρωση Διευθέτησης και κάλυψης ρεμματος Μιχελή στο Δήμο Νέων Λιοσίων (εργολαβία Β53)",
    description_en: "",
    year: 1999,
    typology: "Buildings",
    location: "Ίλιον",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1998,
    budget: 358475.7924
  },
  {
    id: 49,
    name: "Ανακαίνιση υφιστάμενης διπλής σιδηροδρομικής γραμμής Οινόης",
    name_en: "",
    description: "Ανακαίνιση υφιστάμενης διπλής σιδηροδρομικής γραμμής Οινόης - Τιθορέας και Δομοκού - Λάρισας",
    description_en: "",
    year: 2002,
    typology: "Railways",
    location: "Δομοκός",
    region: "Thessaly",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΡΓΑ ΟΣΕ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 1999,
    budget: 15851197.6
  },
  {
    id: 50,
    name: "Σήραγγα Αγίου Ηλία στο τμήμα της Παραϊόνιας Οδού από το τέλος...",
    name_en: "",
    description: "Κατασκευή Σήραγγας Αγίου Ηλία στο τμήμα της Παραϊόνιας Οδού από το τέλος παράκαμψης Γουριάς έως Γαϊδουροπνίχτη",
    description_en: "",
    year: 2003,
    typology: "Tunnels",
    location: "Αιτωλοακαρνανία",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "Κ/Ξ ΕΥΚΛΕΙΔΗΣ ΑΤΕ - ΘΕΜΕΛΗ ΑΕ - ΤΡΙΤΩΝ ΑΤΕ",
    participation: "25%",
    yearStart: 1999,
    budget: 14308803.7
  },
  {
    id: 51,
    name: "Εγνατία οδός : Τμήμα Σήραγγα Ανήλιου - Σήραγγα Αγίου Νικολάου",
    name_en: "",
    description: "Εγνατία οδός : Τμήμα Σήραγγα Ανήλιου - Σήραγγα Αγίου Νικολάου",
    description_en: "",
    year: 2006,
    typology: "Tunnels",
    location: "Ιωάννινα",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΓΝΑΤΙΑ ΟΔΟΣ Α.Ε.",
    contractor: "Κ/Ξ ΑΚΤΩΡ ΑΤΕ - ΕΤΕΘ ΑΕ - ΘΕΜΕΛΗ ΑΕ - ΘΕΜΕΛΙΟΔΟΜΗ ΑΕ",
    participation: "20%",
    yearStart: 2000,
    budget: 108584005.9
  },
  {
    id: 52,
    name: "Στην γραμμή σύνδεσης Λιμένας Ν. Ικονίου με το σιδηροδρομικό δίκτυο...",
    name_en: "",
    description: "Κατασκευή χωματουργικών και τεχνικών έργων στην γραμμή σύνδεσης του λιμένα Ν. Ικονίου με το σιδηροδρομικό δίκτυο τμήμα Χ.Θ. 0+000 έως Χ.Θ. 6+000",
    description_en: "",
    year: 2006,
    typology: "Railways",
    location: "Θεσσαλονίκη",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΡΓΑ ΟΣΕ Α.Ε.",
    contractor: "Κ/Ξ ΑΕΓΕΚ ΑΕ - ΘΕΜΕΛΗ ΑΕ",
    participation: "30%",
    yearStart: 2001,
    budget: 38041321.68
  },
  {
    id: 53,
    name: "Νέο κτίριο αεροσταθμού και διαμόρφωση περιβάλλοντα χώρου στον...",
    name_en: "",
    description: "Νέο κτίριο αεροσταθμού και διαμόρφωση περιβάλλοντα χώρου στον Κρατικό Αερολιμένα Ζακύνθου \"Δ. ΣΟΛΩΜΟΣ\"",
    description_en: "",
    year: 2008,
    typology: "Ports & Marine",
    location: "",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2001,
    budget: 25714922.8
  },
  {
    id: 54,
    name: "Της νέας διπλής σιδηροδρομικής γραμμής με εφαρμογή της μεθόδου...",
    name_en: "",
    description: "Κατασκευή επιδομής της νέας διπλής σιδηροδρομικής γραμμής με εφαρμογή της μεθόδου Σταθερής Επιδομής μεταξύ της Χ.Θ. 374+625 έως Χ.Θ. 381+547 της γραμμής Αθηνών - Θεσσαλονίκης",
    description_en: "",
    year: 2004,
    typology: "Railways",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΡΓΑ ΟΣΕ Α.Ε.",
    contractor: "Κ/Ξ STRABAG Strassen und Tiefbau AG - ΘΕΜΕΛΗ Α.Ε.",
    participation: "40%",
    yearStart: 2002,
    budget: 13423185.46
  },
  {
    id: 55,
    name: "Modernizing the tramway line Nicorita – Piata Chirila – Doi Baieieti",
    name_en: "",
    description: "Modernizing the tramway line Nicorita – Piata Chirila – Doi Baieieti”",
    description_en: "",
    year: 2010,
    typology: "Buildings",
    location: "Iasi, Ρουμανία",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "MUNICIPIUL  IASI",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2008,
    budget: 4500000.0
  },
  {
    id: 56,
    name: "Αξιού",
    name_en: "",
    description: "Κατασκευή Ενωτικής Γραμμής Αξιού",
    description_en: "",
    year: 2006,
    typology: "Railways",
    location: "Θεσσαλονίκη",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΡΓΑ ΟΣΕ Α.Ε.",
    contractor: "COMSA S.A.  (Κατασκευή : Κ/Ξ COMSA SA - ΘΕΜΕΛΗ Α.Ε.)",
    participation: "50%",
    yearStart: 2003,
    budget: 6745641.94
  },
  {
    id: 57,
    name: "Έργα πολιτικού μηχανικού, προμήθεια",
    name_en: "",
    description: "Κατασκευή των έργων πολιτικού μηχανικού, προμήθεια, εγκατάσταση και θέση σε λειτουργία των ηλεκτρομηχανολογικών συστημάτων του σύγχρονου τροχιοδρόμου (ΤΡΑΜ) και μελέτες εφαρμογής τους στην μείζονα περιοχή της Αθήνας",
    description_en: "",
    year: 2004,
    typology: "Railways",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΤΡΑΜ ΑΕ",
    contractor: "Κ/ΞΙΑ ΤΕΡΝΑ Α.Ε. - IMPREGILO SpA (Υπεργολάβος: ΘΕΜΕΛΗ Α.Ε. )",
    participation: "",
    yearStart: 2003,
    budget: 17524310.31
  },
  {
    id: 58,
    name: "Αναβάθμιση των υφισταμένων σιδηροδρομικών γραμμών Κορίνθου",
    name_en: "",
    description: "Αναβάθμιση των υφισταμένων σιδηροδρομικών γραμμών Κορίνθου – Ανδρίτσας και Άργους - Ναυπλίου  (αριθ. 115)",
    description_en: "",
    year: 2008,
    typology: "Railways",
    location: "Κόρινθος",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΘΝΙΚΟΣ ΔΙΑΧΕΙΡΙΣΤΗΣ ΣΙΔΗΡΟΔΡΟΜΙΚΗΣ ΥΠΟΔΟΜΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2004,
    budget: 26500000.0
  },
  {
    id: 59,
    name: "Τα έργα αποκατάστασης στην γραμμή Τραμ και την άμεση όδευση...",
    name_en: "",
    description: "Τα έργα αποκατάστασης στην γραμμή Τραμ και την άμεση όδευση καλωδίων ηλεκτρικού ρεύματος στo Calea Giuleşti, από το Şos. Orhideelor μέχρι την οδό Pătrarului",
    description_en: "",
    year: 2017,
    typology: "Railways",
    location: "",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "REGIA AUTONOMA DE TRANSPORT BUCURESTI",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2004,
    budget: 3487640.87
  },
  {
    id: 60,
    name: "Επί της οδού Κανάρη 3-5 στην στην Πεύκη",
    name_en: "",
    description: "Κατασκευή οικοδομής επί της οδού Κανάρη 3-5 στην στην Πεύκη",
    description_en: "",
    year: 2005,
    typology: "Roadworks",
    location: "Πεύκη",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2004,
    budget: null
  },
  {
    id: 61,
    name: "Τετραόροφη οικοδομή επί pilotis με κατάστημα και υπόγειο",
    name_en: "",
    description: "Τετραόροφη οικοδομή επί pilotis με κατάστημα και υπόγειο (οδός Μακεδονίας 20 & Μαραθώνος 10,  Χαλάνδρι)",
    description_en: "",
    year: 2009,
    typology: "Tunnels",
    location: "Μαραθώνας",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2004,
    budget: 467945.7034
  },
  {
    id: 62,
    name: "REHABILITATION WORKS OF DUDESTI DEPOTCONSTRUCTIONS AND AUTOMATION",
    name_en: "",
    description: "REHABILITATION WORKS OF DUDESTI DEPOTCONSTRUCTIONS AND AUTOMATION",
    description_en: "",
    year: 2007,
    typology: "Buildings",
    location: "Βουκουρέστι, Ρουμανία",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "REGIA AUTONOMA DE TRANSPORT BUCURESTI",
    contractor: "«JV THEMELI SA. - S.C. DRUM ART SRL - S.C. MARI VILA COM SRL - HANNING & KAHL GmbH & Co. KG».",
    participation: "100%",
    yearStart: 2005,
    budget: 7050000.0
  },
  {
    id: 63,
    name: "Αναμόρφωση αρδευτικού Δίκτυο ΤΟΕΒ Παραβόλας Τριχωνίδας Νομού...",
    name_en: "",
    description: "Αναμόρφωση αρδευτικού δικτύου ΤΟΕΒ Παραβόλας Τριχωνίδας Νομού Αιτωλοακαρνανίας",
    description_en: "",
    year: 2010,
    typology: "Utility Networks",
    location: "Αιτωλοακαρρανία",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΝΑ ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ",
    contractor: "«Κ/ΞΙΑ ΑΤΟΜΟΝ Α.Ε. – ΑΝΕΛΙΞΗ Α.Ε.»  (Υπεργολάβος: ΘΕΜΕΛΗ Α.Ε. )",
    participation: "",
    yearStart: 2005,
    budget: 7462092.4
  },
  {
    id: 64,
    name: "Φράγμα Καλαμωτής Νήσου Χίου",
    name_en: "",
    description: "Κατασκευή Φράγματος Καλαμωτής Νήσου Χίου",
    description_en: "",
    year: 2008,
    typology: "Dams",
    location: "Χίος",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΝΑ ΧΙΟΥ",
    contractor: "Κ/Ξ ΕΤΕΘ Α.Ε. - ΘΕΜΕΛΗ Α.Ε.",
    participation: "50%",
    yearStart: 2005,
    budget: 10546388.14
  },
  {
    id: 65,
    name: "Πέντε μονώροφες κατοικίες με υπόγειο",
    name_en: "",
    description: "Πέντε (5) μονώροφες κατοικίες με υπόγειο στο οικόπεδο ιδιοκτησίας  Σ. Βρετού στον Άγιο Λουκά Κέας",
    description_en: "",
    year: 2009,
    typology: "Tunnels",
    location: "Κέα",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2005,
    budget: 227487.81
  },
  {
    id: 66,
    name: "Εγκαταστάσεων Λιμένας Μεστών Ν. Χίου",
    name_en: "",
    description: "Βελτίωση Εγκαταστάσεων Λιμένα Μεστών Ν. Χίου",
    description_en: "",
    year: 2011,
    typology: "Ports & Marine",
    location: "Χίος",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΥΡΓΕΙΟ ΠΕΡ. ΧΩΡ. & Δ.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2006,
    budget: 9364524.29
  },
  {
    id: 67,
    name: "Δύο μονώροφες κατοικίες με υπόγειο",
    name_en: "",
    description: "Δύο (2) μονώροφες κατοικίες με υπόγειο (Αγ. Λουκάς Ν. Κέα)",
    description_en: "",
    year: 2010,
    typology: "Tunnels",
    location: "Κέα",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2006,
    budget: 645161.2903
  },
  {
    id: 68,
    name: "Τροχιόδρομου στη Βούλα και συνοδευτικές εργασίες ένταξης του",
    name_en: "",
    description: "Επέκταση του τροχιόδρομου (ΤΡΑΜ) στη Βούλα και συνοδευτικές εργασίες ένταξης του στο αστικό περιβάλλον των Δήμων Γλυφάδας, Βούλας & Π. Φαλήρου (πεζοδρόμηση Αγγ. Μεταξά, σύστημα απορροής όμβριων Διαδόχου Παύλου & Αγγ. Μεταξά, διαμόρφωση οδού Αχιλλέως)",
    description_en: "",
    year: 2008,
    typology: "Railways",
    location: "Παλαιό Φάληρο",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΤΡΑΜ ΑΕ",
    contractor: "Κ/Ξ ΕΛΛΗΝΙΚΗ ΥΔΡΟΚΑΤΑΣΚΕΥΗ Α.Ε. - ΘΕΜΕΛΗ Α.Ε.",
    participation: "30%",
    yearStart: 2006,
    budget: 12113441.31
  },
  {
    id: 69,
    name: "Σήραγγα Αιγίου στο τμήμα Κιάτο",
    name_en: "",
    description: "Κατασκευή Σήραγγας Αιγίου στο τμήμα Κιάτο - Αίγιο της σιδηροδρομικής γραμμής υψηλών ταχυτήτων Αθηνών - Πατρών",
    description_en: "",
    year: 2011,
    typology: "Railways",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΡΓΑ ΟΣΕ Α.Ε.",
    contractor: "Κ/ΞΙΑ ΤΕΡΝΑ Α.Ε. - ΜΟΧΛΟΣ Α.Ε. - ΑΚΤΩΡ Α.Τ.Ε. (ΘΕΜΕΛΗ Α.Ε. Υπεργολάβος)",
    participation: "100%",
    yearStart: 2006,
    budget: 16071908.38
  },
  {
    id: 70,
    name: "Τετραόροφο κτίριο με υπόγειο και κατάστημα",
    name_en: "",
    description: "Τετραόροφο κτίριο με υπόγειο και κατάστημα (Φωκίωνος Νέγρη 13, Λαύριο)",
    description_en: "",
    year: 2010,
    typology: "Tunnels",
    location: "Λαύριο",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2006,
    budget: 725806.4516
  },
  {
    id: 71,
    name: "Τριώροφη οικοδομή επί Pilotis",
    name_en: "",
    description: "Τριώροφη οικοδομή επί Pilotis, με δύο υπόγεια και δώμα στην οδό Μάρκου Μπότσαρη 22, Βριλήσσια",
    description_en: "",
    year: 2009,
    typology: "Tunnels",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2006,
    budget: 726768.91
  },
  {
    id: 72,
    name: "Τετραόροφη οικοδομή με πυλωτή , υπόγειο πάρκινγκ και δώμα",
    name_en: "",
    description: "Τετραόροφη οικοδομή με πυλωτή , υπόγειο πάρκινγκ και δώμα (Παπάγου Γράμμου και Πίνδου)",
    description_en: "",
    year: 2009,
    typology: "Tunnels",
    location: "Παπάγου",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2007,
    budget: 637096.7742
  },
  {
    id: 73,
    name: "ΔΔ-171/2173139 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΑΓΡΙΝΙΟΥ",
    name_en: "",
    description: "ΔΔ-171/2173139 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΑΓΡΙΝΙΟΥ",
    description_en: "",
    year: 2011,
    typology: "Industrial & Energy",
    location: "Αγρίνιο",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε",
    participation: "100%",
    yearStart: 2008,
    budget: 8736000.0
  },
  {
    id: 74,
    name: "ΔΔ-171/2173148 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΙΩΑΝΝΙΝΩΝ",
    name_en: "",
    description: "ΔΔ-171/2173148 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΙΩΑΝΝΙΝΩΝ",
    description_en: "",
    year: 2010,
    typology: "Industrial & Energy",
    location: "Ιωάννινα",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2008,
    budget: 9163000.0
  },
  {
    id: 75,
    name: "Τετραόροφη οικοδομή επί πιλοτής με υπόγειο",
    name_en: "",
    description: "Τετραόροφη οικοδομή επί πιλοτής με υπόγειο στο οικόπεδο ιδοκτησίας του, στην οδό Μπλέσσα 20, Παπάγου Αττικής",
    description_en: "",
    year: 2010,
    typology: "Tunnels",
    location: "Παπάγου",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2008,
    budget: 439507.24
  },
  {
    id: 76,
    name: "Πάρκου στη θέση Ξεροβούνι Πλατάνου Αιτωλοακαρνανίας",
    name_en: "",
    description: "Κατασκευή Έργων Υποδομής Αιολικού Πάρκου στη θέση Ξεροβούνι Πλατάνου Αιτωλοακαρνανίας",
    description_en: "",
    year: 2012,
    typology: "Industrial & Energy",
    location: "Αιτωλοακαρρανία",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΞΗΡΟΒΟΥΝΙ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2011,
    budget: 24410000.0
  },
  {
    id: 77,
    name: "Τετραόροφη οικοδομή με υπόγειο",
    name_en: "",
    description: "Τετραόροφη οικοδομή με υπόγειο στο οικόπεδο στην Βούλα οδός Ελευθερίου Βενιζέλου 30",
    description_en: "",
    year: 2011,
    typology: "Tunnels",
    location: "Βούλα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΘΕΜΕΛΗ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2009,
    budget: 2258064.52
  },
  {
    id: 78,
    name: "ΔΔ-187/2101115 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΦΙΛΟΘΕΗΣ-ΚΗΦΙΣΙΑΣ",
    name_en: "",
    description: "ΔΔ-187/2101115 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΦΙΛΟΘΕΗΣ-ΚΗΦΙΣΙΑΣ",
    description_en: "",
    year: 2015,
    typology: "Utility Networks",
    location: "Φιλοθέη",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΔΔΗΕ",
    contractor: "Κ/Ξ ΕΚΤΕΡ Α.Ε.  - ΕΡΤΕΚΑ Α.Ε. - ΘΕΜΕΛΗ Α.Ε. - ΙΝΤΡΑΚΑΤ",
    participation: "24%",
    yearStart: 2011,
    budget: 27264000.0
  },
  {
    id: 79,
    name: "ΔΔ-187/2103142 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΑΓΡΙΝΙΟΥ",
    name_en: "",
    description: "ΔΔ-187/2103142 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΑΓΡΙΝΙΟΥ",
    description_en: "",
    year: 2015,
    typology: "Buildings",
    location: "Αγρίνιο",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΔΔΗΕ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2011,
    budget: 9948935.64
  },
  {
    id: 80,
    name: "ΔΔ-187/2103151 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΙΩΑΝΝΙΝΩΝ",
    name_en: "",
    description: "ΔΔ-187/2103151 ΔΙΚΤΥΑ ΠΕΡΙΟΧΗΣ ΙΩΑΝΝΙΝΩΝ",
    description_en: "",
    year: 2015,
    typology: "Buildings",
    location: "Ιωάννινα",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΔΔΗΕ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2011,
    budget: 9421615.72
  },
  {
    id: 81,
    name: "Έργα Πολιτικού Μηχανικού του νέου κέντρου υπερυψηλής τάσης 400/150...",
    name_en: "",
    description: "Έργα Πολιτικού Μηχανικού του νέου κέντρου υπερυψηλής τάσης 400/150 kV στη Μεγαλόπολη",
    description_en: "",
    year: 2012,
    typology: "Buildings",
    location: "Μεγαλόπολη",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΑΔΜΗΕ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2011,
    budget: 1687640.01
  },
  {
    id: 82,
    name: "Τμήματος Γούρνες - Χερσόνησος του Β.Ο.Α.Κ",
    name_en: "",
    description: "Κατασκευή Τμήματος \"Γούρνες - Χερσόνησος \" του Β.Ο.Α.Κ.",
    description_en: "",
    year: 2022,
    typology: "Buildings",
    location: "Χερσόνησος",
    region: "Crete",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΟΡΓΑΝΙΣΜΟΣ ΑΝΑΠΤΥΞΗΣ ΚΡΗΤΗΣ Α.Ε.",
    contractor: "Κ/Ξ ΔΟΜΙΚΗ ΚΡΗΤΗΣ Α.Ε.- ΕΚΤΕΡ Α.Ε. - ΕΡΕΤΒΟ Α.Ε. - ΘΕΜΕΛΗ Α.Ε.",
    participation: "25%",
    yearStart: 2012,
    budget: 46264768.75
  },
  {
    id: 83,
    name: "Πάρκου στη θέση Ξεροβούνι Πλατάνου Αιτωλοακαρνανίας",
    name_en: "",
    description: "Κατασκευή Έργων Υποδομής Αιολικού Πάρκου στη θέση Ξεροβούνι Πλατάνου Αιτωλοακαρνανίας",
    description_en: "",
    year: 2015,
    typology: "Industrial & Energy",
    location: "Αιτωλοακαρρανία",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΞΗΡΟΒΟΥΝΙ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2013,
    budget: 4000000.0
  },
  {
    id: 84,
    name: "ΑΙΟΛΙΚΟΣ ΣΤΑΘΜΟΣ ΠΑΡΑΓΩΓΗΣ ΗΛΕΚΤΡΙΚΗΣ ΕΝΕΡΓΕΙΑΣ ΠΕΡΓΑΝΤΗ ΔΗΜΟΥ...",
    name_en: "",
    description: "ΑΙΟΛΙΚΟΣ ΣΤΑΘΜΟΣ ΠΑΡΑΓΩΓΗΣ ΗΛΕΚΤΡΙΚΗΣ ΕΝΕΡΓΕΙΑΣ \"ΠΕΡΓΑΝΤΗ \" ΔΗΜΟΥ ΑΚΤΙΟΥ - ΒΟΝΙΤΣΑΣ Ν. ΑΙΤ/ΝΙΑΣ",
    description_en: "",
    year: 2020,
    typology: "Industrial & Energy",
    location: "Κως",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΠΕΡΓΑΝΤΗ ΑΚΑΡΝΑΝΙΚΩΝ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2013,
    budget: 16166099.0
  },
  {
    id: 85,
    name: "Έργα πολιτικού μηχανικού, προμήθεια",
    name_en: "",
    description: "Κατασκευή των έργων πολιτικού μηχανικού, προμήθεια, εγκατάσταση και θέση σε λειτουργία των ηλεκτρομηχανολογικών συστημάτων για την επέκταση του τροχιοδρόμου (ΤΡΑΜ) στον Πειραιά κτιριακές εγκαταστάσεις αμαξοστασίου στου Ελληνικό, εργασίες ενίσχυσης και συμπλήρωσης της υποδομής",
    description_en: "",
    year: 2023,
    typology: "Railways",
    location: "Πειραιάς",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΑΤΤΙΚΟ ΜΕΤΡΟ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2013,
    budget: 50353902.28
  },
  {
    id: 86,
    name: "Κατοικιών, Τετράπολις Κέας",
    name_en: "",
    description: "Κατασκευή εξοχικών κατοικιών, Τετράπολις Κέας",
    description_en: "",
    year: 2014,
    typology: "Buildings",
    location: "Κέα",
    region: "Islands",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΤΕΤΡΑΠΟΛΙΣ ΚΕΩΣ Ι.Κ.Ε. - ΤΟΥΡΙΣΤΙΚΕΣ ΕΚΜΕΤΑΛΕΥΣΕΙΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2014,
    budget: 514191.15
  },
  {
    id: 87,
    name: "Της Νέας Διπλής Σιδηροδρομικής Γραμμής στο Τμήμα Ροδοδάφνη",
    name_en: "",
    description: "Κατασκευή Υποδομής της Νέας Διπλής Σιδηροδρομικής Γραμμής στο Τμήμα Ροδοδάφνη - Ψαθόπυργος από Χ.Θ. 91+500 εως Χ.Θ. 113+000 και Σήραγγας Παναγοπούλας",
    description_en: "",
    year: 2020,
    typology: "Railways",
    location: "Αίγιο",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΡΓΑ ΟΣΕ Α.Ε.",
    contractor: "ΙΝΤΡΑΚΑΤ (ΘΕΜΕΛΗ Α.Ε. Υπεργολάβος)",
    participation: "",
    yearStart: 2014,
    budget: 7468022.86
  },
  {
    id: 88,
    name: "Υπολειπόμενων Έργα Υποδομής, Επιδομής, Σηματοδότησης",
    name_en: "",
    description: "Κατασκευή Υπολειπόμενων Έργων Υποδομής, Επιδομής, Σηματοδότησης - Τηλεδιοίκησης, Τηλεπικοινωνιών και Ηλεκτρομηχανολογικών Εγκαταστάσεων Σήραγγων για τη Νέα Σιδηροδρομική Γραμμή Κιάτο - Ροδοδάφνη",
    description_en: "",
    year: 2020,
    typology: "Railways",
    location: "Κιάτο",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΡΓΑ ΟΣΕ Α.Ε.",
    contractor: "ΜΥΤΙΛΗΝΑΙΟΣ Α.Ε. (ΘΕΜΕΛΗ Α.Ε. Υπεργολάβος )",
    participation: "",
    yearStart: 2015,
    budget: 17633060.91
  },
  {
    id: 89,
    name: "Συλλεκτήρες Ομβρίων στην περιοχή Σαλαμίνας της Νήσου Σαλαμίνας",
    name_en: "",
    description: "Κατασκευή Συλλεκτήρων Ομβρίων στην περιοχή Σαλαμίνας της Νήσου Σαλαμίνας",
    description_en: "",
    year: 2020,
    typology: "Utility Networks",
    location: "Σαλαμίνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΠΕΡΙΦΕΡΕΙΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2015,
    budget: 5074043.47
  },
  {
    id: 90,
    name: "Επείγουσες σιδηροδρομικές εργασίες από Χ.Σ. 372+254 έως Χ.Σ....",
    name_en: "",
    description: "Επείγουσες σιδηροδρομικές εργασίες από Χ.Σ. 372+254 έως Χ.Σ. 377+300 γρ. Π-Π για την αποκατάσταση των ζημιών από την εκτροχίαση της εμπορικής αμαξοστοιχίας Τ23500 στις 09/07/2015 (Τέμπη)",
    description_en: "",
    year: 2018,
    typology: "Railways",
    location: "",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΟΣΕ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2016,
    budget: 1251791.38
  },
  {
    id: 91,
    name: "Στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής",
    name_en: "",
    description: "Κατασκευή Παροχετευτικών Αγωγών στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής  (00.092)",
    description_en: "",
    year: 2018,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΔΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2017,
    budget: 420000.0
  },
  {
    id: 92,
    name: "Στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής",
    name_en: "",
    description: "Κατασκευή Παροχετευτικών Αγωγών στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής (00.101)",
    description_en: "",
    year: 2019,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΔΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2018,
    budget: 399079.91
  },
  {
    id: 93,
    name: "Ανακαίνιση Πολυκατοικίας επί της οδού Πατησίων 188, Αθήνα",
    name_en: "",
    description: "Ανακαίνιση Πολυκατοικίας επί της οδού Πατησίων 188, Αθήνα",
    description_en: "",
    year: 2020,
    typology: "Roadworks",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "D T COMPASS ΕΤΑΙΡΕΙΑ ΠΕΡΙΟΡΙΣΜΕΝΗΣ ΕΥΘΥΝΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2019,
    budget: 403000.0
  },
  {
    id: 94,
    name: "Πάρκου στη θέση Καπότη Ακαρνανικών Αιτωλοακαρνανίας",
    name_en: "",
    description: "Κατασκευή Αιολικού Πάρκου στη θέση Καπότη Ακαρνανικών Αιτωλοακαρνανίας",
    description_en: "",
    year: 2020,
    typology: "Industrial & Energy",
    location: "Αιτωλοακαρρανία",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΜΟΡΦΙΑΔΑΚΗΣ ΚΑΙ ΣΥΝΕΡΓΑΤΕΣ Ο.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2019,
    budget: 663000.0
  },
  {
    id: 95,
    name: "Στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής",
    name_en: "",
    description: "Κατασκευή Παροχετευτικών Αγωγών στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής (00.107)",
    description_en: "",
    year: 2019,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΔΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2019,
    budget: 464116.52
  },
  {
    id: 96,
    name: "Στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής",
    name_en: "",
    description: "Κατασκευή Παροχετευτικών Αγωγών στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής (00.118)",
    description_en: "",
    year: 2020,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΔΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2019,
    budget: 372325.52
  },
  {
    id: 97,
    name: "Εργα Πολιτικού Μηχανικού και Η/Μ εγκαταστάσεων για την εγκατάσταση...",
    name_en: "",
    description: "Εργα Πολιτικού Μηχανικού και Η/Μ εγκαταστάσεων για την εγκατάσταση νέων πυλών αυτεπαγωγών 400KW στο ΚΥΤ Μεγαλόπολης",
    description_en: "",
    year: 2020,
    typology: "Utility Networks",
    location: "Μεγαλόπολη",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΑΔΜΗΕ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2019,
    budget: 1798677.59
  },
  {
    id: 98,
    name: "ΑΝΑΚΑΙΝΙΣΗ ΠΟΛΥΚΑΤΟΙΚΙΑΣ ΕΠΙ ΤΗΣ ΟΔΟΥ ΠΑΤΗΣΙΩΝ 188, ΔΗΜΟΥ ΑΘΗΝΑΙΩΝ",
    name_en: "",
    description: "“ΑΝΑΚΑΙΝΙΣΗ ΠΟΛΥΚΑΤΟΙΚΙΑΣ ΕΠΙ ΤΗΣ ΟΔΟΥ ΠΑΤΗΣΙΩΝ 188, ΔΗΜΟΥ ΑΘΗΝΑΙΩΝ”",
    description_en: "",
    year: 2020,
    typology: "Buildings",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "Develop Trust Ε.Π.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2019,
    budget: 403000.0
  },
  {
    id: 99,
    name: "Εγκατάστασης - κλιματισμού",
    name_en: "",
    description: "Προμήθεια και εγκατάσταση κεντρικής εγκατάστασης - κλιματισμού - θέρμανσης - αερισμού στο αμφιθέατρο του κτιρίου \"Αεριοφυλάκιο 1\" της Τεχνόπολις Δήμου Αθηναίων Α.Ε.",
    description_en: "",
    year: 2019,
    typology: "Buildings",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΤΕΧΝΟΠΟΛΗ ΔΗΜΟΥΑΘΗΝΑΙΩΝ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2019,
    budget: 194537.0
  },
  {
    id: 100,
    name: "Track Construction Works on the section between Nagykörút",
    name_en: "",
    description: "Track Construction Works on the section between Nagykörút, Üllői út - Karinthy Frigyes Street",
    description_en: "",
    year: 2020,
    typology: "Buildings",
    location: "Βουδαπέστη, Ουγγαρία",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "Budapest Transport Company ZRt",
    contractor: "TTDExpert Zrt. (η ΘΕΜΕΛΗ είναι δανειοπάροχος και υπεργολάβος)",
    participation: "",
    yearStart: 2020,
    budget: 170000.0
  },
  {
    id: 101,
    name: "Ανάπλαση Παραλιακού Μετώπου Ακτής Κουμουνδούρου",
    name_en: "",
    description: "Ανάπλαση Παραλιακού Μετώπου Ακτής Κουμουνδούρου (Μικρολίμανο)",
    description_en: "",
    year: 2023,
    typology: "Buildings",
    location: "Πειραιάς",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΗΜΟΣ ΠΕΙΡΑΙΑ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2020,
    budget: 3395081.0
  },
  {
    id: 102,
    name: "Μεταφοράς νερού από τις πηγές της Κ.Κ. πηδήματος μέχρι την Καλαμάτα",
    name_en: "",
    description: "Αντικατάσταση κεντρικού αγωγού μεταφοράς νερού από τις πηγές της Κ.Κ. πηδήματος μέχρι την Καλαμάτα",
    description_en: "",
    year: 2020,
    typology: "Utility Networks",
    location: "Καλαμάτα",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΥΑ ΚΑΛΑΜΑΤΑΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2020,
    budget: 6984201.84
  },
  {
    id: 103,
    name: "ΕΝΕΡΓΕΙΑΚΗ ΑΝΑΒΑΘΜΙΣΗ ΜΕΣΩ ΤΗΣ ΑΝΑΒΑΘΜΙΣΗΣ ΒΑΤΟΤΗΤΑΣ ΠΕΖΟΔΡΟΜΙΩΝ...",
    name_en: "",
    description: "«ΕΝΕΡΓΕΙΑΚΗ ΑΝΑΒΑΘΜΙΣΗ ΜΕΣΩ ΤΗΣ ΑΝΑΒΑΘΜΙΣΗΣ ΒΑΤΟΤΗΤΑΣ ΠΕΖΟΔΡΟΜΙΩΝ ΚΑΙ ΟΔΩΝ ΑΠΟ ΤΗΝ 1Η ΕΩΣ ΤΗΝ 7Η Δ.Κ.»",
    description_en: "",
    year: 2021,
    typology: "Industrial & Energy",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΗΜΟΣ ΑΘΗΝΑΙΩΝ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2021,
    budget: 15261355.64
  },
  {
    id: 104,
    name: "Προστασίας SW με Αγωγό Προστασίας με ενσωματωμένες οπτινές ίνες...",
    name_en: "",
    description: "Αντικατάσταση κοινού Αγωγού Προστασίας SW με Αγωγό Προστασίας με ενσωματωμένες οπτινές ίνες τύπου OPGW σε Γ.Μ. 150kV (Υποέργο Α) και Γ.Μ. 400kV (Υποέργο Β)",
    description_en: "",
    year: 2021,
    typology: "Utility Networks",
    location: "",
    region: "",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΑΔΜΗΕ Α.Ε.",
    contractor: "Κ/Ξ ΘΕΜΕΛΗ Α.Ε. - ΑΚΤΙΝΑ Α.Ε.",
    participation: "50%",
    yearStart: 2020,
    budget: 1096305.6
  },
  {
    id: 105,
    name: "Πάρκου Ελευσίνας",
    name_en: "",
    description: "Κατασκευή Έργων Υποδομής Επιχειρηματικού Πάρκου Ελευσίνας",
    description_en: "",
    year: 2020,
    typology: "Buildings",
    location: "Ελευσίνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΠΙΧΕΙΠΑ.ΠΑ. ΕΛΕΥΣΙΝΑΣ ΑΕ",
    contractor: "ΘΕΜΕΛΗ Α,Ε,",
    participation: "100%",
    yearStart: 2020,
    budget: 5239411.62
  },
  {
    id: 106,
    name: "Στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής",
    name_en: "",
    description: "Κατασκευή Παροχετευτικών Αγωγών στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής (00.126)",
    description_en: "",
    year: 2020,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΔΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2020,
    budget: 683389.05
  },
  {
    id: 107,
    name: "Στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής",
    name_en: "",
    description: "Κατασκευή Παροχετευτικών Αγωγών στο Δίκτυο Διανομής χαμηλής πίεσως έως 4 BAR στο Νομό Αττικής (00.130)",
    description_en: "",
    year: 2021,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΔΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2020,
    budget: 985000.0
  },
  {
    id: 108,
    name: "ΜΕΤΑΤΟΠΙΣΗ ΤΜΗΜΑΤΟΣ ΑΠΟΧΕΤΕΥΤΙΚΟΥ ΔΙΚΤΥΟΥ VACUM Μετατόπιση...",
    name_en: "",
    description: "ΜΕΤΑΤΟΠΙΣΗ ΤΜΗΜΑΤΟΣ ΑΠΟΧΕΤΕΥΤΙΚΟΥ ΔΙΚΤΥΟΥ VACUM (ΠΕΠ ΑΤΤΙΚΗΣ) Μετατόπιση τμήματος αποχετευτικού δικτύου Vacum ( ΠΕΠ Αττικής)",
    description_en: "",
    year: 2021,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΗΜΟΣ ΣΑΛΑΜΙΝΑΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2020,
    budget: 58221.91
  },
  {
    id: 109,
    name: "Νέος Αγωγός Μεταφοράς νερού από Υδροληψία Μύρτου για την Ενίσχυση...",
    name_en: "",
    description: "Νέος Αγωγός Μεταφοράς νερού από Υδροληψία Μύρτου για την Ενίσχυση του Ταμιευτήρα Μπραμιανού",
    description_en: "",
    year: 2020,
    typology: "Utility Networks",
    location: "Κως",
    region: "Islands",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΜΕΔΙ/ ΔΝΣΗ ΑΝΤΙΠΛΗΜΜΥΡΙΚΩΝ ΕΡΓΩΝ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2020,
    budget: 9766925.0
  },
  {
    id: 110,
    name: "Στο Δίκτυο Διανομής Χαμηλής Πίεσης έως 4bar στο Νομό Αττικής",
    name_en: "",
    description: "Κατασκευή Παροχετευτικών Αγωγών στο Δίκτυο Διανομής Χαμηλής Πίεσης έως 4bar στο Νομό Αττικής\t(00.150)",
    description_en: "",
    year: 2022,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΔΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2021,
    budget: 960000.0
  },
  {
    id: 111,
    name: "Στο Δίκτυο Διανομής Χαμηλής Πίεσης έως 4bar στο Νομό Αττικής",
    name_en: "",
    description: "Κατασκευή Παροχετευτικών Αγωγών στο Δίκτυο Διανομής Χαμηλής Πίεσης έως 4bar στο Νομό Αττικής\t(00.157)",
    description_en: "",
    year: 2022,
    typology: "Utility Networks",
    location: "Αττική",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΔΑ ΑΤΤΙΚΗΣ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2021,
    budget: 980000.0
  },
  {
    id: 112,
    name: "ΚΑΤΑΣΚΕΥΗ ΕΝΑΕΡΙΑΣ Γ.Μ. 150KV ΜΑΝΤΟΥΔΙ - ΣΚΙΑΘΟΣ",
    name_en: "",
    description: "ΚΑΤΑΣΚΕΥΗ ΕΝΑΕΡΙΑΣ Γ.Μ. 150KV ΜΑΝΤΟΥΔΙ - ΣΚΙΑΘΟΣ",
    description_en: "",
    year: 2022,
    typology: "Buildings",
    location: "Εύβοια",
    region: "Central Greece",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΑΔΜΗΕ Α.Ε.",
    contractor: "Κ/Ξ ΘΕΜΕΛΗ - ELCTROMONTAJ",
    participation: "45%",
    yearStart: 2021,
    budget: 1980000.0
  },
  {
    id: 113,
    name: "ΕΠΕΚΤΑΣΗ-ΒΕΛΤΙΩΣΗ ΠΕΔΙΟΥ ΕΛΙΓΜΩΝ ΚΡΑΤΙΚΟΥ ΑΕΡΟΛΙΜΕΝΑ ΧΙΟΥ ΟΜΗΡΟΣ...",
    name_en: "",
    description: "ΕΠΕΚΤΑΣΗ-ΒΕΛΤΙΩΣΗ ΠΕΔΙΟΥ ΕΛΙΓΜΩΝ ΚΡΑΤΙΚΟΥ ΑΕΡΟΛΙΜΕΝΑ ΧΙΟΥ \"ΟΜΗΡΟΣ\" ΚΑΙ ΣΥΝΑΦΗ ΕΡΓΑ",
    description_en: "",
    year: 2021,
    typology: "Ports & Marine",
    location: "Χίος",
    region: "Islands",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΥΠΟΜΕΔΙ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2021,
    budget: 19954191.81
  },
  {
    id: 114,
    name: "ΟΚΤΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΤΡΙΑΝΤΑΕΞΙ ΔΙΑΜΕΡΙΣΜΑΤΩΝ ΜΕ PILOTIS ΚΑΙ...",
    name_en: "",
    description: "«ΟΚΤΑΩΡΟΦΗ ΠΟΛΥΚΑΤΟΙΚΙΑ ΤΡΙΑΝΤΑΕΞΙ ΔΙΑΜΕΡΙΣΜΑΤΩΝ ΜΕ PILOTIS ΚΑΙ ΥΠΟΓΕΙΟ», στην οδό Πρωτέως 60, στον Δήμο Παλαιού Φαλήρου",
    description_en: "",
    year: 2024,
    typology: "Buildings",
    location: "Παλαιό Φάληρο",
    region: "Attica",
    architect: "",
    size: "",
    status: "Completed",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "Develop Trust Ε.Π.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2021,
    budget: 2165736.0
  },
  {
    id: 115,
    name: "ΕΠΕΚΤΑΣΗ ΑΜΑΞΟΣΤΑΣΙΟΥ ΤΡΑΜ ΣΤΟ ΕΛΛΗΝΙΚΟ RFP-360/19",
    name_en: "",
    description: "ΕΠΕΚΤΑΣΗ ΑΜΑΞΟΣΤΑΣΙΟΥ ΤΡΑΜ ΣΤΟ ΕΛΛΗΝΙΚΟ RFP-360/19",
    description_en: "",
    year: 2022,
    typology: "Railways",
    location: "Ελληνικό",
    region: "Attica",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΑΤΤΙΚΟ ΜΕΤΡΟ Α.Ε.",
    contractor: "Κ/Ξ ΤΕΡΝΑ Α.Ε. - ΘΕΜΕΛΗ Α.Ε.",
    participation: "50%",
    yearStart: 2022,
    budget: 14750000.0
  },
  {
    id: 116,
    name: "Δίκτυα ακαθάρτων στον Δήμο Μαραθώνα",
    name_en: "",
    description: "Κατασκευή δικτύων ακαθάρτων στον Δήμο Μαραθώνα — Εργολαβία Α-459.",
    description_en: "",
    year: 2022,
    typology: "Utility Networks",
    location: "Μαραθώνας",
    region: "Attica",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΕΥΔΑΠ Α.Ε.",
    contractor: "Κ/ΞΙΑ ΕΚΤΕΡ Α.Ε. - ΕΡΕΤΒΟ Α.Ε. - ΘΕΜΕΛΗ Α.Ε. - ΤΕΧΝΙΚΗ ΕΤΑΙΡΕΙΑ ΧΡΟΣΤΟΦΟΡΟΣ ΚΩΝΣΤΑΝΤΙΝΙΔΗΣ Α.Ε.",
    participation: "25%",
    yearStart: 2022,
    budget: 72850000.0
  },
  {
    id: 117,
    name: "Δίκτυο πολυαιθυλενίου, στα δίκτυα χαμηλής πίεσης της πόλης της...",
    name_en: "",
    description: "Επέκταση δικτύου πολυαιθυλενίου, και συνδέσεις οικιακών και εμπορικών πελατών στα δίκτυα χαμηλής πίεσης (4 bar) της πόλης της Φλώρινας της Περιφέρειας Δυτικής Μακεδονίας.",
    description_en: "",
    year: 2022,
    typology: "Utility Networks",
    location: "Φλώρινα",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΔΑ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2022,
    budget: 18700000.0
  },
  {
    id: 118,
    name: "Υδραγωγείου κοινότητας Διμηνιού και παραλιακής ζώνης Δήμου Σικυωνιών",
    name_en: "",
    description: "Αντικατάσταση εσωτερικού υδραγωγείου κοινότητας Διμηνιού και παραλιακής ζώνης Δήμου Σικυωνιών",
    description_en: "",
    year: 2022,
    typology: "Utility Networks",
    location: "Σικυώνα",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΥΑ ΣΙΚΥΩΝΙΩΝ",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2022,
    budget: 7543826.13
  },
  {
    id: 119,
    name: "0321-CS1799 - NEW COGENERATION PLANT UNI U-7000",
    name_en: "",
    description: "PROJECT: 0321-CS1799 - NEW COGENERATION PLANT (GT-6) UNI U-7000",
    description_en: "",
    year: 2023,
    typology: "Industrial & Energy",
    location: "Κόρινθος",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "MOTOR OIL",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2023,
    budget: 3950000.0
  },
  {
    id: 120,
    name: "Μεταξύ Ρίου - Κάτω Αχαϊας",
    name_en: "",
    description: "Συντήρηση μετρικής σιδηροδρομικής γραμμής μεταξύ Ρίου - Κάτω Αχαϊας» (Α.Δ. 2112Α)",
    description_en: "",
    year: 2023,
    typology: "Railways",
    location: "Πάτρα",
    region: "Peloponnese",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΟΣΕ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "50%",
    yearStart: 2023,
    budget: 1084975.74
  },
  {
    id: 121,
    name: "Και αλλαγών Συντήρησης Γραμμής Αθηνών",
    name_en: "",
    description: "Εργασίες συντήρησης γραμμών και αλλαγών στην περιοχή δικαιοδοσίας του τμήματος Συντήρησης Γραμμής Αθηνών» (Α.Δ. 2121Α)",
    description_en: "",
    year: 2023,
    typology: "Railways",
    location: "Αθήνα",
    region: "Attica",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΟΣΕ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2023,
    budget: 4332151.51
  },
  {
    id: 122,
    name: "Δίκτυο Πολυαιθυλενίου στην πόλη της Φλώρινας",
    name_en: "",
    description: "«Επέκταση δικτύου Πολυαιθυλενίου και συνδέσεις οικιακών και εμπορικών πελατών δικτύου χαμηλής πίεσης (4bar) στην πόλη της Φλώρινας»",
    description_en: "",
    year: 2024,
    typology: "Utility Networks",
    location: "Φλώρινα",
    region: "Northern Greece",
    architect: "",
    size: "",
    status: "In Progress",
    dateCompleted: "",
    image: "",
    images: [],
    mapX: null,
    mapY: null,
    client: "ΔΕΔΑ Α.Ε.",
    contractor: "ΘΕΜΕΛΗ Α.Ε.",
    participation: "100%",
    yearStart: 2024,
    budget: 4368150.0
  }
];
