/**
 * THEMELI — Core namespace and constants
 */

// ========== I18N ==========
const LANG = window.location.pathname.includes('/el/') ? 'el' : 'en';
const BASE = window.location.pathname.match(/\/(en|el)\//) ? '../' : '';
/* THEMELI — Projects loader (static data) */

async function fetchProjects() {
  return typeof PROJECTS !== 'undefined' ? PROJECTS : [];
}
/* THEMELI — Internationalization data */

// UI strings (non-content translations)
const I18N = {
  en: {
    projects: 'Projects', project: 'Project',
    copied: 'Copied!', copyAddress: 'Copy Address', copyNumber: 'Copy Number',
    clearAll: 'Clear All',
    typ: {},
    loc: {
      'Αθήνα': 'Athens', 'Πειραιάς': 'Piraeus', 'Θεσσαλονίκη': 'Thessaloniki',
      'Κως': 'Kos', 'Κόρινθος': 'Corinth', 'Λάρισα': 'Larissa', 'Πάτρα': 'Patras',
      'Ελευσίνα': 'Elefsina', 'Χαλανδρί': 'Chalandri', 'Φιλοθέη': 'Filothei',
      'Αργυρούπολη': 'Argyroupoli', 'Βούλα': 'Voula', 'Παπάγου': 'Papagou',
      'Πεύκη': 'Peyki', 'Νέα Ιωνία': 'Nea Ionia', 'Λαύριο': 'Lavrio',
      'Παλαιό Φάληρο': 'Palaio Faliro', 'Ελληνικό': 'Elliniko', 'Σαλαμίνα': 'Salamina',
      'Μαραθώνας': 'Marathon', 'Ίλιον': 'Ilion',
      'Κέα': 'Kea', 'Χίος': 'Chios', 'Λέσβος': 'Lesvos', 'Εύβοια': 'Evia',
      'Κεφαλλονιά': 'Kefalonia', 'Μυτιλήνη': 'Mytilene',
      'Ναύπλιο': 'Nafplio', 'Καλαμάτα': 'Kalamata', 'Αίγιο': 'Aigio',
      'Κιάτο': 'Kiato', 'Σικυώνα': 'Sikyon', 'Μεγαλόπολη': 'Megalopoli',
      'Αγρίνιο': 'Agrinio', 'Αιτωλοακαρνανία': 'Aitoloakarnania',
      'Αιτωλοακαρρανία': 'Aitoloakarnania', 'Μεσοχώρα': 'Mesochora',
      'Τρίκαλα': 'Trikala', 'Μουζάκι': 'Mouzaki',
      'Λαμία': 'Lamia', 'Δομοκός': 'Domokos',
      'Ιωάννινα': 'Ioannina', 'Φλώρινα': 'Florina',
      'Κιλκίς': 'Kilkis', 'Σταυροχώρι': 'Stavrochori',
      'Χερσόνησος': 'Hersonissos',
      'Χαλκίδα': 'Chalkida', 'Γαλάτσι': 'Galatsi', 'Κρήτη': 'Crete',
      'Αττική': 'Attica',
      'Βουκουρέστι, Ρουμανία': 'Bucharest, Romania',
      'Βουδαπέστη, Ουγγαρία': 'Budapest, Hungary',
      'Iasi, Ρουμανία': 'Iași, Romania'
    }
  },
  el: {
    projects: 'Έργα', project: 'Έργο',
    copied: 'Αντιγράφηκε!', copyAddress: 'Αντιγραφή Διεύθυνσης', copyNumber: 'Αντιγραφή Αριθμού',
    clearAll: 'Καθαρισμός',
    typ: {
      'Buildings': 'Κτίρια',
      'Railways': 'Σιδηρόδρομοι',
      'Roadworks': 'Οδοποιία',
      'Tunnels': 'Σήραγγες',
      'Industrial & Energy': 'Βιομηχανικά & Ενέργεια',
      'Utility Networks': 'Δίκτυα Κοινής Ωφέλειας',
      'Dams': 'Φράγματα',
      'Ports & Marine': 'Λιμάνια & Θαλάσσια',
      'Urban Redevelopment': 'Αστική Ανάπλαση'
    },
    stat: {
      'Completed': 'Ολοκληρωμένο',
      'In Progress': 'Σε Εξέλιξη'
    }
  }
};
const T = I18N[LANG];

// Subsidiary data loaded from external subsidiaries-data.js (generated by build)
// Prepend BASE to all asset paths at runtime
function prefixSubsPaths(data) {
  if (!data || !BASE) return data;
  const result = {};
  for (const [key, sub] of Object.entries(data)) {
    const s = JSON.parse(JSON.stringify(sub)); // deep clone
    if (s.logo) s.logo = BASE + s.logo;
    if (s.featured) {
      s.featured.forEach(f => { if (f.img) f.img = BASE + f.img; });
    }
    if (s.featuredGroups) {
      s.featuredGroups.forEach(g => {
        if (g.items) g.items.forEach(f => { if (f.img) f.img = BASE + f.img; });
        if (g.gallery) g.gallery = g.gallery.map(p => BASE + p);
      });
    }
    result[key] = s;
  }
  return result;
}

// Attach subsData to T for backward compatibility with subsidiaries page
const rawSubsData = (typeof SUBS_DATA !== 'undefined') ? SUBS_DATA[LANG] : {};
T.subsData = prefixSubsPaths(rawSubsData);

/* THEMELI — Menu & navigation */

// ========== MENU ==========
const hamburger = document.getElementById('hamburger');
const navOverlay = document.getElementById('navOverlay');

if (hamburger && navOverlay) {
  const mainContent = document.querySelector('main');
  const footer = document.querySelector('footer');

  function openMenu() {
    hamburger.classList.add('is-active');
    navOverlay.classList.add('is-open');
    hamburger.setAttribute('aria-expanded', 'true');
    document.body.style.overflow = 'hidden';
    // Focus trap: make main/footer inert
    if (mainContent) mainContent.setAttribute('inert', '');
    if (footer) footer.setAttribute('inert', '');
  }

  function closeMenu() {
    hamburger.classList.remove('is-active');
    navOverlay.classList.remove('is-open');
    hamburger.setAttribute('aria-expanded', 'false');
    document.body.style.overflow = '';
    // Remove focus trap
    if (mainContent) mainContent.removeAttribute('inert');
    if (footer) footer.removeAttribute('inert');
    hamburger.focus();
  }

  hamburger.addEventListener('click', () => {
    if (navOverlay.classList.contains('is-open')) {
      closeMenu();
    } else {
      openMenu();
    }
  });

  navOverlay.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', () => {
      closeMenu();
    });
  });

  // Close menu when clicking the backdrop (overlay itself, not links)
  navOverlay.addEventListener('click', (e) => {
    if (e.target === navOverlay) closeMenu();
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && navOverlay.classList.contains('is-open')) {
      closeMenu();
    }
  });
}
/* THEMELI — Scroll reveal animations */

// ========== SCROLL REVEAL ==========
const revealObserver = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('is-visible');
    }
  });
}, {
  threshold: 0.1,
  rootMargin: '0px 0px -60px 0px'
});

document.querySelectorAll('.reveal, .reveal-left, .reveal-right, .reveal-scale, .timeline-bar').forEach(el => {
  revealObserver.observe(el);
});
/* THEMELI — Typewriter effect */

// ========== TYPEWRITER EFFECT ==========
document.querySelectorAll('.timeline-opener').forEach(el => {
  const origHTML = el.innerHTML;
  el.classList.add('typewriter');

  // Parse original HTML into a temp container
  const temp = document.createElement('div');
  temp.innerHTML = origHTML;

  const walkAndWrap = (node) => {
    const frag = document.createDocumentFragment();
    node.childNodes.forEach(child => {
      if (child.nodeType === Node.TEXT_NODE) {
        child.textContent.split('').forEach(ch => {
          const span = document.createElement('span');
          span.className = 'tw-char';
          span.textContent = ch;
          frag.appendChild(span);
        });
      } else if (child.nodeType === Node.ELEMENT_NODE) {
        const clone = child.cloneNode(false);
        clone.appendChild(walkAndWrap(child));
        frag.appendChild(clone);
      }
    });
    return frag;
  };

  el.innerHTML = '';
  el.appendChild(walkAndWrap(temp));

  // Gather all tw-char spans in order
  const chars = el.querySelectorAll('.tw-char');

  // Observe for scroll reveal
  const twObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        twObserver.unobserve(el);
        el.classList.add('typing');
        let i = 0;
        const speed = 14; // ms per batch
        const batchSize = 2; // reveal 2 chars per tick
        const tick = () => {
          if (i < chars.length) {
            for (let b = 0; b < batchSize && i < chars.length; b++, i++) {
              chars[i].classList.add('tw-visible');
            }
            requestAnimationFrame(() => setTimeout(tick, speed));
          }
        };
        tick();
      }
    });
  }, { threshold: 0.1 });

  twObserver.observe(el);
});
/* THEMELI — Scroll utilities */

// ========== PAGE HEADER SCROLL FADE ==========
const pageHeader = document.querySelector('.page-header');
if (pageHeader) {
  let phTicking = false;
  let phLastScrollY = 0;
  window.addEventListener('scroll', () => {
    if (!phTicking) {
      requestAnimationFrame(() => {
        const currentY = window.scrollY;
        if (currentY <= 80) {
          pageHeader.classList.remove('is-hidden');
        } else if (currentY < phLastScrollY) {
          pageHeader.classList.remove('is-hidden');
        } else {
          pageHeader.classList.add('is-hidden');
        }
        phLastScrollY = currentY;
        phTicking = false;
      });
      phTicking = true;
    }
  }, { passive: true });
}

// ========== SCROLL TO TOP ==========
const scrollTopBtn = document.getElementById('scrollTop');
if (scrollTopBtn) {
  scrollTopBtn.addEventListener('click', () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  });

  let stTicking = false;
  window.addEventListener('scroll', () => {
    if (!stTicking) {
      requestAnimationFrame(() => {
        scrollTopBtn.classList.toggle('is-visible', window.scrollY > 300);
        stTicking = false;
      });
      stTicking = true;
    }
  });
}

// ========== SMOOTH PARALLAX ON HERO ==========
const hero = document.querySelector('.hero');
const heroEst = document.querySelector('.hero-est');

if (hero && heroEst) {
  let ticking = false;
  window.addEventListener('scroll', () => {
    if (!ticking) {
      requestAnimationFrame(() => {
        const scrollY = window.scrollY;
        const heroHeight = hero.offsetHeight;
        if (scrollY < heroHeight) {
          const progress = scrollY / heroHeight;
          heroEst.style.transform = `translateY(calc(-50% + ${scrollY * 0.3}px))`;
          heroEst.style.opacity = 1 - progress * 1.5;
        }
        ticking = false;
      });
      ticking = true;
    }
  });
}
/* THEMELI — Timeline navigation */

// ========== TIMELINE NAV ==========
const timelineNav = document.getElementById('timelineNav');
if (timelineNav) {
  const navButtons = timelineNav.querySelectorAll('.timeline-nav-year');
  const progressBar = document.getElementById('timelineNavProgress');

  // Click to scroll
  navButtons.forEach(btn => {
    btn.addEventListener('click', () => {
      const targetId = btn.getAttribute('data-target');
      const target = document.getElementById(targetId);
      if (target) {
        const offset = 120;
        const top = target.getBoundingClientRect().top + window.scrollY - offset;
        window.scrollTo({ top, behavior: 'smooth' });
      }
    });
  });

  // Track active era on scroll
  const eraIds = Array.from(navButtons).map(btn => btn.getAttribute('data-target'));
  const eraElements = eraIds.map(id => document.getElementById(id)).filter(Boolean);

  function updateActiveYear() {
    const scrollY = window.scrollY + 200;
    let activeIndex = 0;

    eraElements.forEach((el, i) => {
      if (el.offsetTop <= scrollY) {
        activeIndex = i;
      }
    });

    navButtons.forEach((btn, i) => {
      btn.classList.toggle('is-active', i === activeIndex);
    });

    // Update progress bar
    if (progressBar && navButtons.length > 1) {
      const pct = (activeIndex / (navButtons.length - 1)) * 100;
      progressBar.style.width = pct + '%';
    }
  }

  let navTicking = false;
  window.addEventListener('scroll', () => {
    if (!navTicking) {
      requestAnimationFrame(() => {
        updateActiveYear();
        navTicking = false;
      });
      navTicking = true;
    }
  });

  updateActiveYear();
}
/* THEMELI — Project data rendering */

// ========== PROJECTS: DATA-DRIVEN RENDERING ==========
const projGridView = document.getElementById('projGridView');
const projListView = document.getElementById('projListView');
const projMapView = document.getElementById('projMapView');
const mapInner = document.getElementById('mapInner');

// Load and render projects
if (projGridView) {
(async function renderProjects() {
const projectData = (await fetchProjects()).sort((a, b) => (b.year || 0) - (a.year || 0));
if (!projectData.length) return;
  // Escape HTML entities
  function esc(str) {
    const d = document.createElement('div');
    d.textContent = str;
    return d.innerHTML;
  }

  // Helper: translate typology for display
  function tTyp(v) { return T.typ[v] || v; }
  // Helper: translate location for display
  function tLoc(v) { return (T.loc && T.loc[v]) || v; }
  // Helper: pick localized name/description
  function lName(p) { return LANG === 'el' ? p.name : (p.name_en || p.name); }
  function lDesc(p) { return LANG === 'el' ? (p.description || '') : (p.description_en || p.description || ''); }

  // Render grid cards
  projectData.forEach(p => {
    const imgStyle = p.image ? ` style="background-image:url('${esc(p.image)}')"` : '';
    projGridView.insertAdjacentHTML('beforeend',
      `<a class="proj-card" data-typology="${esc(p.typology)}" data-status="${esc(p.status || '')}" data-region="${esc(p.region || '')}" href="project.html?id=${p.id}">
        <div class="proj-card-img"${imgStyle}></div>
        <div class="proj-card-info"><span class="proj-card-name">${esc(lName(p))}</span><span class="proj-card-year">${p.year}</span></div>
        <span class="proj-card-tag">${esc(tTyp(p.typology))}</span>
      </a>`
    );
  });

  // Render list rows
  if (projListView) {
    projectData.forEach(p => {
      projListView.insertAdjacentHTML('beforeend',
        `<a class="proj-row" data-typology="${esc(p.typology)}" data-status="${esc(p.status || '')}" data-region="${esc(p.region || '')}" href="project.html?id=${p.id}"><span class="proj-col proj-col-name">${esc(lName(p))}</span><span class="proj-col proj-col-type">${esc(tTyp(p.typology))}</span><span class="proj-col proj-col-loc">${esc(tLoc(p.location))}</span><span class="proj-col proj-col-year">${p.year}</span></a>`
      );
    });
  }

  // Render map dots and lines with tooltip cards
  if (mapInner) {
    const LINEAR_TYPES = ['Railways', 'Tunnels', 'Roadworks'];

    projectData.forEach(p => {
      if (p.mapX == null || p.mapY == null) return;
      // Skip international projects (coords outside Greece map bounds)
      if (p.mapX < 10 || p.mapX > 95 || p.mapY < 10 || p.mapY > 98) return;

      // Determine if this is a linear project with route points
      const hasPolyline = Array.isArray(p.mapPoints) && p.mapPoints.length >= 2;
      const isLinear = hasPolyline || (LINEAR_TYPES.includes(p.typology) && p.mapX2 != null && p.mapY2 != null);
      const tooltipImg = p.image ? ` style="background-image:url('${esc(p.image)}')"` : '';

      if (isLinear) {
        // Linear projects: draw polyline + two clickable endpoint dots (no middle dot)
        const points = hasPolyline ? p.mapPoints : [[p.mapX, p.mapY], [p.mapX2, p.mapY2]];
        const ptsStr = points.map(pt => `${pt[0]},${pt[1]}`).join(' ');
        const first = points[0];
        const last = points[points.length - 1];

        // SVG polyline (hidden until activated)
        mapInner.insertAdjacentHTML('beforeend',
          `<svg class="proj-map-line" data-typology="${esc(p.typology)}" data-region="${esc(p.region || '')}" data-status="${esc(p.status || '')}" data-project="${p.id}" viewBox="0 0 100 100" preserveAspectRatio="none">
            <polyline points="${ptsStr}" fill="none" stroke="rgba(255,115,30,0.6)" stroke-width="0.3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>`
        );

        // First endpoint (has the tooltip)
        mapInner.insertAdjacentHTML('beforeend',
          `<a class="proj-map-dot has-line${first[0] > 50 ? ' tooltip-left' : ''}" style="left:${first[0]}%;top:${first[1]}%" data-typology="${esc(p.typology)}" data-status="${esc(p.status || '')}" data-region="${esc(p.region || '')}" data-id="${p.id}" href="project.html?id=${p.id}">
            <div class="proj-map-tooltip">
              <div class="proj-map-tooltip-img"${tooltipImg}></div>
              <div class="proj-map-tooltip-body">
                <span class="proj-map-tooltip-name">${esc(lName(p))}</span>
                <span class="proj-map-tooltip-year">${p.year}</span>
              </div>
              <span class="proj-map-tooltip-tag">${esc(tTyp(p.typology))}</span>
            </div>
          </a>`
        );

        // Second endpoint (clickable, links to same project, no tooltip)
        mapInner.insertAdjacentHTML('beforeend',
          `<a class="proj-map-dot has-line" style="left:${last[0]}%;top:${last[1]}%" data-typology="${esc(p.typology)}" data-status="${esc(p.status || '')}" data-region="${esc(p.region || '')}" data-id="${p.id}" href="project.html?id=${p.id}"></a>`
        );
      } else {
        // Point projects: single dot with tooltip
        const dotX = p.mapX;
        const dotY = p.mapY;
        mapInner.insertAdjacentHTML('beforeend',
          `<a class="proj-map-dot${dotX > 50 ? ' tooltip-left' : ''}" style="left:${dotX}%;top:${dotY}%" data-typology="${esc(p.typology)}" data-status="${esc(p.status || '')}" data-region="${esc(p.region || '')}" data-id="${p.id}" href="project.html?id=${p.id}">
            <div class="proj-map-tooltip">
              <div class="proj-map-tooltip-img"${tooltipImg}></div>
              <div class="proj-map-tooltip-body">
                <span class="proj-map-tooltip-name">${esc(lName(p))}</span>
                <span class="proj-map-tooltip-year">${p.year}</span>
              </div>
              <span class="proj-map-tooltip-tag">${esc(tTyp(p.typology))}</span>
            </div>
          </a>`
        );
      }
    });

  }

  // Update initial count
  const projCount = document.getElementById('projCount');
  if (projCount) {
    projCount.textContent = projectData.length + ' ' + (projectData.length !== 1 ? T.projects : T.project);
  }

  // Reveal the grid now that cards have been injected
  projGridView.classList.add('is-visible');
})();
}
/* THEMELI — Projects view switching, map, filter */

// ========== PROJECTS VIEW SWITCHING ==========
const projViewToggles = document.getElementById('projViewToggles');

if (projViewToggles && projGridView) {
  const viewBtns = projViewToggles.querySelectorAll('.proj-view-btn');
  const views = { grid: projGridView, list: projListView, map: projMapView };

  viewBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      const target = btn.getAttribute('data-view');
      viewBtns.forEach(b => b.classList.remove('is-active'));
      btn.classList.add('is-active');
      Object.entries(views).forEach(([key, el]) => {
        if (el) el.style.display = key === target ? '' : 'none';
      });
      if (window._resetMapZoom) window._resetMapZoom();

      // Hide filters/chips on map view
      const filterToggle = document.getElementById('projFilterToggle');
      const chips = document.getElementById('projChips');
      const filters = document.getElementById('projFilters');
      const isMap = target === 'map';
      const projCount = document.getElementById('projCount');
      if (filterToggle) filterToggle.style.display = isMap ? 'none' : '';
      if (projCount) projCount.style.display = isMap ? 'none' : '';
      if (chips) chips.style.display = isMap ? 'none' : '';
      if (filters && isMap) { filters.classList.remove('is-open'); filters.style.display = 'none'; }
      if (filters && !isMap) filters.style.display = '';
    });
  });
}

// ========== MAP ZOOM & PAN ==========
const mapViewport = document.getElementById('mapViewport');
const mapZoomIn = document.getElementById('mapZoomIn');
const mapZoomOut = document.getElementById('mapZoomOut');

if (mapViewport && mapInner) {
  const MIN_SCALE = 1;
  const MAX_SCALE = 3;
  const ZOOM_STEP = 0.5;
  let scale = 1;
  let panX = 0;
  let panY = 0;
  let isDragging = false;
  let startX = 0;
  let startY = 0;
  let touchMoved = false;
  let lastTouchEnd = 0;

  // Pinch state
  let initialPinchDist = 0;
  let initialPinchScale = 1;

  function applyTransform(smooth) {
    mapInner.style.transition = smooth ? 'transform 0.35s cubic-bezier(0.25,0.46,0.45,0.94)' : 'none';
    mapInner.style.transform = `translate(${panX}px, ${panY}px) scale(${scale})`;
    mapViewport.classList.toggle('is-zoomed', scale > 1);
    // Counter-scale dots so they don't grow with zoom, but keep them tappable
    const cs = Math.max(0.5, 1 / scale);
    mapViewport.style.setProperty('--map-counter-scale', cs);
    // Tooltip must undo BOTH dot counter-scale AND parent map zoom
    // Effective inherited scale on tooltip = scale * cs
    // To get tooltip back to 1.0: multiply by 1 / (scale * cs)
    mapViewport.style.setProperty('--map-tooltip-restore', 1 / (scale * cs));
  }

  function clampPan() {
    if (scale <= 1) { panX = 0; panY = 0; return; }
    const rect = mapViewport.getBoundingClientRect();
    const maxPanX = (rect.width * (scale - 1)) / 2;
    const maxPanY = (rect.height * (scale - 1)) / 2;
    panX = Math.max(-maxPanX, Math.min(maxPanX, panX));
    panY = Math.max(-maxPanY, Math.min(maxPanY, panY));
  }

  function zoomTo(newScale, centerX, centerY, smooth) {
    const prev = scale;
    scale = Math.max(MIN_SCALE, Math.min(MAX_SCALE, newScale));
    if (centerX !== undefined && centerY !== undefined) {
      const rect = mapViewport.getBoundingClientRect();
      const cx = centerX - rect.left - rect.width / 2;
      const cy = centerY - rect.top - rect.height / 2;
      panX = panX - cx * (scale / prev - 1);
      panY = panY - cy * (scale / prev - 1);
    }
    if (scale <= 1) { panX = 0; panY = 0; }
    clampPan();
    applyTransform(smooth !== false);
  }

  // Button zoom
  mapZoomIn.addEventListener('click', () => { zoomTo(scale + ZOOM_STEP); });
  mapZoomOut.addEventListener('click', () => { zoomTo(scale - ZOOM_STEP); });

  // Double-click zoom
  mapViewport.addEventListener('dblclick', (e) => {
    if (scale > 1) {
      zoomTo(1);
    } else {
      zoomTo(2, e.clientX, e.clientY);
    }
  });

  // Expose reset
  window._resetMapZoom = function() {
    if (scale > 1) { scale = 1; panX = 0; panY = 0; applyTransform(true); }
  };

  // ── Mouse pan ──
  mapViewport.addEventListener('mousedown', (e) => {
    if (scale <= 1) return;
    isDragging = true;
    startX = e.clientX - panX;
    startY = e.clientY - panY;
    e.preventDefault();
  });
  window.addEventListener('mousemove', (e) => {
    if (!isDragging) return;
    panX = e.clientX - startX;
    panY = e.clientY - startY;
    clampPan();
    applyTransform(false);
  });
  window.addEventListener('mouseup', () => { isDragging = false; });

  // ── Touch pan + pinch zoom ──
  function getTouchDist(e) {
    const dx = e.touches[0].clientX - e.touches[1].clientX;
    const dy = e.touches[0].clientY - e.touches[1].clientY;
    return Math.hypot(dx, dy);
  }

  mapViewport.addEventListener('touchstart', (e) => {
    touchMoved = false;
    if (e.touches.length === 2) {
      // Pinch start
      isDragging = false;
      initialPinchDist = getTouchDist(e);
      initialPinchScale = scale;
    } else if (e.touches.length === 1 && scale > 1) {
      // Single-finger pan (only when zoomed)
      isDragging = true;
      startX = e.touches[0].clientX - panX;
      startY = e.touches[0].clientY - panY;
    }
  }, { passive: true });

  mapViewport.addEventListener('touchmove', (e) => {
    touchMoved = true;
    if (e.touches.length === 2 && initialPinchDist) {
      // Pinch zoom
      const dist = getTouchDist(e);
      const ratio = dist / initialPinchDist;
      const midX = (e.touches[0].clientX + e.touches[1].clientX) / 2;
      const midY = (e.touches[0].clientY + e.touches[1].clientY) / 2;
      zoomTo(initialPinchScale * ratio, midX, midY, false);
      e.preventDefault();
    } else if (isDragging && e.touches.length === 1) {
      // Pan
      panX = e.touches[0].clientX - startX;
      panY = e.touches[0].clientY - startY;
      clampPan();
      applyTransform(false);
      e.preventDefault();
    }
  }, { passive: false });

  mapViewport.addEventListener('touchend', (e) => {
    if (e.touches.length < 2) initialPinchDist = 0;
    if (e.touches.length === 0) isDragging = false;
    lastTouchEnd = Date.now();
  }, { passive: true });

  // ── Focus + line visibility helpers ──
  function showLineForDot(dot) {
    if (!dot) return;
    mapInner.classList.add('has-focus');
    const id = dot.dataset.id;
    if (id) {
      // Show the line
      const line = mapInner.querySelector(`.proj-map-line[data-project="${id}"]`);
      if (line) line.classList.add('is-active');
      // Activate ALL dots for this project (both endpoints)
      mapInner.querySelectorAll(`.proj-map-dot[data-id="${id}"]`).forEach(d => d.classList.add('is-active'));
    }
  }
  function hideAllLines() {
    mapInner.classList.remove('has-focus');
    mapInner.querySelectorAll('.proj-map-line.is-active').forEach(l => l.classList.remove('is-active'));
    mapInner.querySelectorAll('.proj-map-dot.is-active').forEach(d => d.classList.remove('is-active'));
  }

  // ── Desktop click → toggle focus + line ──
  mapViewport.addEventListener('click', (e) => {
    if (Date.now() - lastTouchEnd < 300) return; // handled by touch
    const dot = e.target.closest('.proj-map-dot');
    if (!dot) {
      mapViewport.querySelectorAll('.proj-map-dot.is-active').forEach(d => d.classList.remove('is-active'));
      hideAllLines();
      return;
    }
    if (dot.classList.contains('is-active')) {
      window.location.href = dot.href;
      return;
    }
    e.preventDefault();
    mapViewport.querySelectorAll('.proj-map-dot.is-active').forEach(d => d.classList.remove('is-active'));
    hideAllLines();
    dot.classList.add('is-active');
    showLineForDot(dot);
  });

  // ── Touch dot interaction (tap-to-preview) ──
  mapViewport.addEventListener('touchend', (e) => {
    if (touchMoved || e.touches.length > 0) return;
    const dot = e.target.closest('.proj-map-dot');
    if (!dot) {
      mapViewport.querySelectorAll('.proj-map-dot.is-active').forEach(d => d.classList.remove('is-active'));
      hideAllLines();
      return;
    }
    if (dot.classList.contains('is-active')) {
      window.location.href = dot.href;
      return;
    }
    e.preventDefault();
    mapViewport.querySelectorAll('.proj-map-dot.is-active').forEach(d => d.classList.remove('is-active'));
    hideAllLines();
    dot.classList.add('is-active');
    showLineForDot(dot);
  });

  // Block click on touch devices (touchend handles dots)
  mapViewport.addEventListener('click', (e) => {
    const dot = e.target.closest('.proj-map-dot');
    if (dot && Date.now() - lastTouchEnd < 300) e.preventDefault();
  });
}

// ========== PROJECTS FILTER (multi-category with chips) ==========
const projFilterToggle = document.getElementById('projFilterToggle');
const projFilters = document.getElementById('projFilters');
const projChips = document.getElementById('projChips');
const projApply = document.getElementById('projApply');
const projClearAll = document.getElementById('projClearAll');

if (projFilterToggle && projFilters) {
  // Active filters: { status: Set, typology: Set, region: Set }
  const activeFilters = { status: new Set(), typology: new Set(), region: new Set() };

  // Toggle filter panel (reset zoom to avoid overlap)
  projFilterToggle.addEventListener('click', () => {
    projFilters.classList.toggle('is-open');
    projFilterToggle.classList.toggle('is-active');
    if (window._resetMapZoom) window._resetMapZoom();
  });

  // Close filter panel when clicking outside
  document.addEventListener('click', (e) => {
    if (!projFilters.contains(e.target) && !projFilterToggle.contains(e.target) && projFilters.classList.contains('is-open')) {
      projFilters.classList.remove('is-open');
      projFilterToggle.classList.remove('is-active');
    }
  });

  // Toggle filter buttons on click and apply immediately
  projFilters.addEventListener('click', (e) => {
    const btn = e.target.closest('.proj-filter-btn');
    if (!btn) return;
    btn.classList.toggle('is-active');
    applyFilters();
  });

  // Apply filters
  function applyFilters() {
    // Read active buttons into filter sets
    activeFilters.status.clear();
    activeFilters.typology.clear();
    activeFilters.region.clear();
    projFilters.querySelectorAll('.proj-filter-btn.is-active').forEach(btn => {
      const cat = btn.getAttribute('data-category');
      const val = btn.getAttribute('data-filter');
      if (activeFilters[cat]) activeFilters[cat].add(val);
    });

    let visibleCount = 0;
    const hasFilters = activeFilters.status.size || activeFilters.typology.size || activeFilters.region.size;

    function matchesFilters(el) {
      if (!hasFilters) return true;
      if (activeFilters.status.size && !activeFilters.status.has(el.getAttribute('data-status'))) return false;
      if (activeFilters.typology.size && !activeFilters.typology.has(el.getAttribute('data-typology'))) return false;
      if (activeFilters.region.size && !activeFilters.region.has(el.getAttribute('data-region'))) return false;
      return true;
    }

    // Filter grid cards
    document.querySelectorAll('.proj-card').forEach(card => {
      const match = matchesFilters(card);
      card.classList.toggle('is-hidden', !match);
      if (match) visibleCount++;
    });

    // Filter list rows
    document.querySelectorAll('.proj-row:not(.proj-row-header)').forEach(row => {
      row.classList.toggle('is-hidden', !matchesFilters(row));
    });

    // Filter map dots (clear active tooltips on hidden dots)
    document.querySelectorAll('.proj-map-dot').forEach(dot => {
      const hidden = !matchesFilters(dot);
      dot.classList.toggle('is-hidden', hidden);
      if (hidden) dot.classList.remove('is-active');
    });

    // Filter map lines
    document.querySelectorAll('.proj-map-line').forEach(line => {
      line.classList.toggle('is-hidden', !matchesFilters(line));
    });

    // Update count
    const projCount = document.getElementById('projCount');
    if (projCount) {
      projCount.textContent = visibleCount + ' ' + (visibleCount !== 1 ? T.projects : T.project);
    }

    // Update filter toggle state
    projFilterToggle.classList.toggle('is-active', hasFilters || projFilters.classList.contains('is-open'));

    renderChips();
  }

  // Render chips
  function renderChips() {
    if (!projChips) return;
    projChips.innerHTML = '';
    const hasAny = activeFilters.status.size || activeFilters.typology.size || activeFilters.region.size;
    if (!hasAny) return;

    // Create chip for each active filter
    for (const [cat, values] of Object.entries(activeFilters)) {
      values.forEach(val => {
        // Use the button's visible text for the chip label
        const btn = projFilters.querySelector(`.proj-filter-btn[data-category="${cat}"][data-filter="${val}"]`);
        const label = btn ? btn.textContent : val;
        const chip = document.createElement('button');
        chip.className = 'proj-chip';
        chip.innerHTML = `<span class="proj-chip-x">&times;</span> ${label}`;
        chip.addEventListener('click', () => {
          activeFilters[cat].delete(val);
          if (btn) btn.classList.remove('is-active');
          applyFilters();
        });
        projChips.appendChild(chip);
      });
    }

    // Clear All chip
    const clearBtn = document.createElement('button');
    clearBtn.className = 'proj-chips-clear';
    clearBtn.textContent = '\u2014 ' + (T.clearAll || 'Clear All');
    clearBtn.addEventListener('click', clearAllFilters);
    projChips.appendChild(clearBtn);
  }

  // Clear all filters
  function clearAllFilters() {
    activeFilters.status.clear();
    activeFilters.typology.clear();
    activeFilters.region.clear();
    projFilters.querySelectorAll('.proj-filter-btn.is-active').forEach(b => b.classList.remove('is-active'));
    applyFilters();
  }

  // Apply button
  if (projApply) projApply.addEventListener('click', applyFilters);

  // Clear All button (in filter panel)
  if (projClearAll) projClearAll.addEventListener('click', clearAllFilters);
}

// ========== LIST VIEW SORTING ==========
if (projListView) {
  const colMap = {
    name: '.proj-col-name',
    typology: '.proj-col-type',
    location: '.proj-col-loc',
    year: '.proj-col-year'
  };
  let currentSort = null;
  let sortDesc = false;

  projListView.addEventListener('click', (e) => {
    const btn = e.target.closest('.proj-sort-btn');
    if (!btn) return;

    const key = btn.getAttribute('data-sort');

    // Toggle direction or switch column
    if (currentSort === key) {
      sortDesc = !sortDesc;
    } else {
      currentSort = key;
      sortDesc = false;
    }

    // Update button states
    projListView.querySelectorAll('.proj-sort-btn').forEach(b => {
      b.classList.remove('is-sorted', 'is-desc');
    });
    btn.classList.add('is-sorted');
    if (sortDesc) btn.classList.add('is-desc');

    // Get all data rows (not the header)
    const rows = Array.from(projListView.querySelectorAll('.proj-row:not(.proj-row-header)'));
    const selector = colMap[key];

    rows.sort((a, b) => {
      const aVal = a.querySelector(selector)?.textContent.trim() || '';
      const bVal = b.querySelector(selector)?.textContent.trim() || '';

      // Numeric sort for year
      if (key === 'year') {
        return sortDesc ? (parseInt(bVal) - parseInt(aVal)) : (parseInt(aVal) - parseInt(bVal));
      }
      // Alphabetical for text columns
      const cmp = aVal.localeCompare(bVal);
      return sortDesc ? -cmp : cmp;
    });

    // Re-append rows in sorted order
    rows.forEach(row => projListView.appendChild(row));
  });
}
/* THEMELI — Subsidiaries detail & lightbox */

// ========== SUBSIDIARIES REACTIVE DETAIL ==========
const subsData = T.subsData;

const subsGrid = document.getElementById('subsGrid');
const subDetail = document.getElementById('subDetail');
const subBack = document.getElementById('subBack');
const subName = document.getElementById('subName');
const subSubtitle = document.getElementById('subSubtitle');
const subDesc = document.getElementById('subDesc');
const subLogo = document.getElementById('subLogo');

if (subsGrid && subDetail) {

  // Gallery lightbox function
  const openGallery = (images, startIndex) => {
    let idx = startIndex || 0;
    const lb = document.createElement('div');
    lb.className = 'lightbox';
    lb.innerHTML = `
      <button class="lightbox-close" aria-label="Close">&times;</button>
      <button class="lightbox-arrow lightbox-prev" aria-label="Previous">&lsaquo;</button>
      <img class="lightbox-img" src="${images[idx]}" alt="">
      <button class="lightbox-arrow lightbox-next" aria-label="Next">&rsaquo;</button>
      <div class="lightbox-counter">${idx + 1} / ${images.length}</div>`;
    document.body.appendChild(lb);
    document.body.style.overflow = 'hidden';

    const img = lb.querySelector('.lightbox-img');
    const counter = lb.querySelector('.lightbox-counter');
    const updateArrows = () => {
      lb.querySelector('.lightbox-prev').style.visibility = images.length > 1 ? 'visible' : 'hidden';
      lb.querySelector('.lightbox-next').style.visibility = images.length > 1 ? 'visible' : 'hidden';
    };
    const show = () => {
      img.src = images[idx];
      counter.textContent = (idx + 1) + ' / ' + images.length;
    };
    updateArrows();

    requestAnimationFrame(() => {
      requestAnimationFrame(() => lb.classList.add('is-visible'));
    });

    function handler(e) {
      if (e.key === 'Escape') close();
      if (e.key === 'ArrowLeft') { idx = (idx - 1 + images.length) % images.length; show(); }
      if (e.key === 'ArrowRight') { idx = (idx + 1) % images.length; show(); }
    }

    const close = () => {
      document.removeEventListener('keydown', handler);
      document.body.style.overflow = '';
      lb.classList.remove('is-visible');
      setTimeout(() => lb.remove(), 300);
    };
    lb.querySelector('.lightbox-close').addEventListener('click', close);
    lb.querySelector('.lightbox-prev').addEventListener('click', (e) => {
      e.stopPropagation();
      idx = (idx - 1 + images.length) % images.length;
      show();
    });
    lb.querySelector('.lightbox-next').addEventListener('click', (e) => {
      e.stopPropagation();
      idx = (idx + 1) % images.length;
      show();
    });
    lb.addEventListener('click', e => { if (e.target === lb) close(); });
    document.addEventListener('keydown', handler);
  };

  // Show subsidiary detail view
  function showSubDetail(key, pushHistory) {
    const data = subsData[key];
    if (!data) return;

    subName.textContent = data.name;
    subSubtitle.textContent = data.subtitle;
    subDesc.innerHTML = data.desc;
    subLogo.setAttribute('data-sub', key);
    subLogo.innerHTML = `<img src="${data.logo}" alt="${data.name}">`;

    // Populate featured grid
    const subFeatured = document.getElementById('subFeatured');
    if (subFeatured) {
      const renderCard = (f) => {
        const hasImg = f.img && f.img !== '';
        const imgTag = hasImg
          ? `<img class="sub-featured-img" src="${f.img}" alt="${f.name}" loading="lazy">`
          : `<div class="sub-featured-img sub-featured-img--empty"></div>`;
        return `<div class="sub-featured-card"${hasImg ? ` data-lightbox="${f.img}"` : ''}>
          ${imgTag}
          <div class="sub-featured-info">
            <span class="sub-featured-name">${f.name}</span>
          </div>
        </div>`;
      };

      if (data.featuredGroups && data.featuredGroups.length) {
        subFeatured.innerHTML = data.featuredGroups.map((group, i) => {
          const divider = i > 0 ? '<div class="sub-featured-divider"></div>' : '';
          return `${divider}<div class="sub-featured-group">
            <div class="sub-featured-group-header">
              <h3 class="sub-featured-group-title">${group.title}</h3>
              <span class="sub-featured-group-subtitle">${group.subtitle}</span>
            </div>
            <div class="sub-featured-group-cards">
              ${group.items.map(renderCard).join('')}
            </div>
          </div>`;
        }).join('');
        subFeatured.classList.add('sub-featured-grid--grouped');
        subFeatured.classList.remove('sub-featured-grid');
      } else if (data.featured && data.featured.length) {
        subFeatured.innerHTML = data.featured.map(renderCard).join('');
        subFeatured.classList.add('sub-featured-grid');
        subFeatured.classList.remove('sub-featured-grid--grouped');
      } else {
        subFeatured.innerHTML = '';
        subFeatured.classList.remove('sub-featured-grid', 'sub-featured-grid--grouped');
      }

      // Attach lightbox to grouped cards (with gallery)
      if (data.featuredGroups) {
        data.featuredGroups.forEach((group, gi) => {
          const gallery = group.gallery || group.items.filter(f => f.img).map(f => f.img);
          const groupEl = subFeatured.querySelectorAll('.sub-featured-group')[gi];
          if (groupEl) {
            groupEl.querySelectorAll('[data-lightbox]').forEach(card => {
              card.addEventListener('click', () => {
                const src = card.getAttribute('data-lightbox');
                const startIdx = gallery.indexOf(src);
                openGallery(gallery, startIdx >= 0 ? startIdx : 0);
              });
            });
          }
        });
      }

      // Attach lightbox to simple featured cards
      if (data.featured) {
        const allImgs = data.featured.filter(f => f.img).map(f => f.img);
        subFeatured.querySelectorAll('[data-lightbox]').forEach(card => {
          card.addEventListener('click', () => {
            const src = card.getAttribute('data-lightbox');
            const startIdx = allImgs.indexOf(src);
            openGallery(allImgs, startIdx >= 0 ? startIdx : 0);
          });
        });
      }
    }

    // Transition: hide grid, show detail
    subsGrid.classList.add('is-hidden');
    subDetail.classList.add('is-active');
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        subDetail.classList.add('is-visible');
      });
    });

    window.scrollTo({ top: 0, behavior: 'smooth' });

    // Update URL hash
    if (pushHistory) {
      window.history.pushState({ sub: key }, '', '#' + key);
    }
  }

  // Show logo grid
  function showSubGrid() {
    subDetail.classList.remove('is-visible');
    setTimeout(() => {
      subDetail.classList.remove('is-active');
      subsGrid.classList.remove('is-hidden');
    }, 400);
  }

  // Click on a subsidiary logo
  document.querySelectorAll('[data-sub]').forEach(el => {
    el.addEventListener('click', () => {
      const key = el.getAttribute('data-sub');
      showSubDetail(key, true);
    });
  });

  // Back button
  if (subBack) {
    subBack.addEventListener('click', () => {
      window.history.back();
    });
  }

  // Handle browser back/forward
  window.addEventListener('popstate', () => {
    const hash = window.location.hash.slice(1);
    if (hash && subsData[hash]) {
      showSubDetail(hash, false);
    } else {
      showSubGrid();
    }
  });

  // Handle initial load with hash
  if (window.location.hash) {
    const key = window.location.hash.slice(1);
    if (subsData[key]) {
      showSubDetail(key, false);
    }
  }
}
/* THEMELI — Project detail page */

// ========== PROJECT DETAIL PAGE ==========
const pdetDetail = document.getElementById('projectDetail');

if (pdetDetail) {
  // Support both ?id=X (direct) and #X (legacy fallback)
  const params = new URLSearchParams(window.location.search);
  const hashId = window.location.hash.replace('#', '');

  // Normalize hash-based URLs to query params for SEO
  if (hashId && !params.get('id')) {
    window.history.replaceState(null, '', `project.html?id=${hashId}`);
  }

  const projectId = parseInt(params.get('id'), 10) || parseInt(hashId, 10);

  // Sanitise a string for use inside a CSS url()
  function cssUrl(str) {
    return str ? str.replace(/['"\\()]/g, '\\$&') : '';
  }

  // Load project data
  (async function() {
  const allProjects = await fetchProjects();
  const currentIdx = allProjects.findIndex(p => Number(p.id) === projectId);
  const project = currentIdx !== -1 ? allProjects[currentIdx] : null;

  if (project) {
    // Content
    const tTyp = v => (T.typ[v] || v);
    const tLoc = v => (T.loc && T.loc[v]) || v;
    const pName = LANG === 'el' ? project.name : (project.name_en || project.name);
    const pDesc = LANG === 'el' ? (project.description || '') : (project.description_en || project.description || '');

    // Set page title and update meta tags for SEO
    document.title = `THEMELI — ${pName}`;
    const canonicalUrl = window.location.origin + window.location.pathname + '?id=' + project.id;
    const metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc) metaDesc.content = pDesc;
    const ogTitle = document.querySelector('meta[property="og:title"]');
    if (ogTitle) ogTitle.content = document.title;
    const ogDesc = document.querySelector('meta[property="og:description"]');
    if (ogDesc) ogDesc.content = pDesc;
    const ogUrl = document.querySelector('meta[property="og:url"]');
    if (ogUrl) ogUrl.content = canonicalUrl;
    const canonical = document.querySelector('link[rel="canonical"]');
    if (canonical) canonical.href = canonicalUrl;
    if (project.image) {
      const ogImg = document.querySelector('meta[property="og:image"]');
      if (ogImg) {
        // OG images require absolute URLs for social sharing
        const imgUrl = project.image.startsWith('http') ? project.image : window.location.origin + '/' + project.image.replace(/^\.\.\//, '');
        ogImg.content = imgUrl;
      }
    }

    // Hero image
    const heroImg = document.getElementById('pdetHeroImg');
    if (project.image) {
      heroImg.style.backgroundImage = `url('${cssUrl(project.image)}')`;
      heroImg.classList.add('has-image');
    }
    document.getElementById('pdetTag').textContent = tTyp(project.typology);
    document.getElementById('pdetTitle').textContent = pName;
    document.getElementById('pdetYear').textContent = project.year;
    document.getElementById('pdetLocation').textContent = tLoc(project.location) || '—';
    document.getElementById('pdetTypology').textContent = tTyp(project.typology);
    document.getElementById('pdetDesc').textContent = pDesc;

    // Gallery
    const galleryEl = document.getElementById('pdetGallery');
    const galleryImgs = Array.isArray(project.images) ? project.images.filter(Boolean) : [];
    if (galleryImgs.length && galleryEl) {
      galleryImgs.forEach((url, i) => {
        const img = document.createElement('img');
        img.src = url;
        img.className = 'pdet-gallery-img';
        img.alt = project.name + ' — ' + (i + 1);
        img.loading = 'lazy';
        img.addEventListener('click', () => openGalleryLightbox(galleryImgs, i));
        galleryEl.appendChild(img);
      });
    }

    // Info board
    const archEl = document.getElementById('pdetArchitect');
    const sizeEl = document.getElementById('pdetSize');
    const statusEl = document.getElementById('pdetStatus');
    const dateCompEl = document.getElementById('pdetDateCompleted');
    const infoLocEl = document.getElementById('pdetInfoLocation');
    const infoTypEl = document.getElementById('pdetInfoTypology');

    archEl.textContent = project.architect || '—';
    sizeEl.textContent = project.size || '—';
    const tStat = v => (T.stat && T.stat[v]) || v;
    statusEl.textContent = tStat(project.status || 'Completed');
    dateCompEl.textContent = project.dateCompleted || String(project.year);
    infoLocEl.textContent = tLoc(project.location) || '—';
    infoTypEl.textContent = tTyp(project.typology);

    // Hide empty optional rows
    if (!project.architect) document.getElementById('pdetInfoArchitect').style.display = 'none';
    if (!project.size) document.getElementById('pdetInfoSize').style.display = 'none';

    // Related projects — same typology, excluding current
    const related = allProjects
      .filter(p => p.typology === project.typology && p.id !== project.id)
      .slice(0, 4);

    const relatedGrid = document.getElementById('pdetRelatedGrid');
    const relatedSection = document.getElementById('pdetRelated');

    if (related.length > 0 && relatedGrid) {
      related.forEach(p => {
        const imgStyle = p.image ? `background-image:url('${cssUrl(p.image)}')` : '';
        relatedGrid.insertAdjacentHTML('beforeend',
          `<a class="pdet-related-card" href="project.html?id=${p.id}">
            <div class="pdet-related-card-img" style="${imgStyle}"></div>
            <div class="pdet-related-card-body">
              <span class="pdet-related-card-name">${LANG === 'el' ? p.name : (p.name_en || p.name)}</span>
              <span class="pdet-related-card-meta">${tTyp(p.typology)} &middot; ${tLoc(p.location) || ''}</span>
            </div>
          </a>`
        );
      });
    } else if (relatedSection) {
      relatedSection.style.display = 'none';
    }

    // Adjacent project navigation (loops around)
    const prevProject = allProjects[(currentIdx - 1 + allProjects.length) % allProjects.length];
    const nextProject = allProjects[(currentIdx + 1) % allProjects.length];

    const prevLink = document.getElementById('pdetPrev');
    const nextLink = document.getElementById('pdetNext');
    const prevName = document.getElementById('pdetPrevName');
    const nextName = document.getElementById('pdetNextName');

    prevLink.href = `project.html?id=${prevProject.id}`;
    prevName.textContent = LANG === 'el' ? prevProject.name : (prevProject.name_en || prevProject.name);

    nextLink.href = `project.html?id=${nextProject.id}`;
    nextName.textContent = LANG === 'el' ? nextProject.name : (nextProject.name_en || nextProject.name);

    // Staggered reveal animation
    requestAnimationFrame(() => {
      pdetDetail.classList.add('is-loaded');
    });
  } else {
    // Project not found — redirect back
    window.location.href = 'projects.html';
  }
  })();
}

// ========== GALLERY LIGHTBOX ==========
function openGalleryLightbox(images, startIndex) {
  let idx = startIndex;
  const overlay = document.createElement('div');
  overlay.className = 'lightbox';
  overlay.innerHTML = `
    <button class="lightbox-close">&times;</button>
    ${images.length > 1 ? '<button class="lightbox-arrow lightbox-prev">&#8249;</button>' : ''}
    <img class="lightbox-img" src="${images[idx]}" alt="">
    ${images.length > 1 ? '<button class="lightbox-arrow lightbox-next">&#8250;</button>' : ''}
    ${images.length > 1 ? '<div class="lightbox-counter">' + (idx + 1) + ' / ' + images.length + '</div>' : ''}
  `;
  document.body.appendChild(overlay);
  document.body.style.overflow = 'hidden';
  requestAnimationFrame(() => overlay.classList.add('is-visible'));

  const img = overlay.querySelector('.lightbox-img');
  const counter = overlay.querySelector('.lightbox-counter');

  function show(i) {
    idx = (i + images.length) % images.length;
    img.src = images[idx];
    if (counter) counter.textContent = (idx + 1) + ' / ' + images.length;
  }

  function handler(e) {
    if (e.key === 'Escape') close();
    if (e.key === 'ArrowLeft' && prev) show(idx - 1);
    if (e.key === 'ArrowRight' && next) show(idx + 1);
  }

  function close() {
    document.removeEventListener('keydown', handler);
    document.body.style.overflow = '';
    overlay.classList.remove('is-visible');
    setTimeout(() => overlay.remove(), 300);
  }

  overlay.querySelector('.lightbox-close').addEventListener('click', close);
  overlay.addEventListener('click', (e) => { if (e.target === overlay) close(); });
  const prev = overlay.querySelector('.lightbox-prev');
  const next = overlay.querySelector('.lightbox-next');
  if (prev) prev.addEventListener('click', () => show(idx - 1));
  if (next) next.addEventListener('click', () => show(idx + 1));
  document.addEventListener('keydown', handler);
}
/* THEMELI — Email & phone popups */

// ========== EMAIL POPUP ==========
document.querySelectorAll('.email-trigger').forEach(trigger => {
  trigger.addEventListener('click', (e) => {
    e.preventDefault();
    const wrapper = trigger.closest('.email-wrapper');
    // Close any other open popups
    document.querySelectorAll('.email-wrapper.active, .phone-wrapper.active').forEach(w => {
      if (w !== wrapper) w.classList.remove('active');
    });
    wrapper.classList.toggle('active');
  });
});

document.querySelectorAll('.email-copy').forEach(btn => {
  btn.addEventListener('click', () => {
    const email = btn.dataset.email;
    navigator.clipboard.writeText(email).then(() => {
      btn.textContent = T.copied;
      btn.classList.add('copied');
      setTimeout(() => {
        btn.textContent = T.copyAddress;
        btn.classList.remove('copied');
        btn.closest('.email-wrapper').classList.remove('active');
      }, 1500);
    });
  });
});

// ========== PHONE POPUP ==========
document.querySelectorAll('.phone-trigger').forEach(trigger => {
  trigger.addEventListener('click', (e) => {
    e.preventDefault();
    const wrapper = trigger.closest('.phone-wrapper');
    document.querySelectorAll('.phone-wrapper.active, .email-wrapper.active').forEach(w => {
      if (w !== wrapper) w.classList.remove('active');
    });
    wrapper.classList.toggle('active');
  });
});

document.querySelectorAll('.phone-copy').forEach(btn => {
  btn.addEventListener('click', () => {
    const phone = btn.dataset.phone;
    navigator.clipboard.writeText(phone).then(() => {
      btn.textContent = T.copied;
      btn.classList.add('copied');
      setTimeout(() => {
        btn.textContent = T.copyNumber;
        btn.classList.remove('copied');
        btn.closest('.phone-wrapper').classList.remove('active');
      }, 1500);
    });
  });
});

// Close popups when clicking outside
document.addEventListener('click', (e) => {
  if (!e.target.closest('.email-wrapper') && !e.target.closest('.phone-wrapper')) {
    document.querySelectorAll('.email-wrapper.active, .phone-wrapper.active').forEach(w => {
      w.classList.remove('active');
    });
  }
});
/* THEMELI — Canvas Terminal Background
   3D block-fly logo assembly animation (homepage only) */

(function initTerminalBackground() {
  const canvas = document.getElementById('terminal-bg');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');

  let width, height;

  /* ── Logo block-fly assembly ── */
  const logoSvg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 140 94" fill="none">' +
    '<path d="M139.831 0H0V18.7278H139.831V0Z" fill="white"/>' +
    '<path d="M104.012 93.668H139.831V74.7873H111.717L69.9588 32.7759L28.2832 74.7873H0V93.668H36.0783L70.0247 59.5446L104.012 93.668Z" fill="white"/>' +
    '</svg>';
  const logoImg = new Image();
  let logoBlocks = null;
  const blockSize = 5;
  let logoGridW = 0, logoGridH = 0;
  const logoBuildDelay = 1500;
  const logoBuildDuration = 5000;
  let logoBuildStartTime = 0;

  logoImg.onload = function () {
    const offW = 280, offH = 188;
    const offCanvas = document.createElement('canvas');
    offCanvas.width = offW;
    offCanvas.height = offH;
    const offCtx = offCanvas.getContext('2d');
    offCtx.drawImage(logoImg, 0, 0, offW, offH);
    const imgData = offCtx.getImageData(0, 0, offW, offH);

    logoGridW = Math.floor(offW / blockSize);
    logoGridH = Math.floor(offH / blockSize);
    logoBlocks = [];

    for (let row = 0; row < logoGridH; row++) {
      for (let col = 0; col < logoGridW; col++) {
        const px = Math.floor(col * blockSize + blockSize / 2);
        const py = Math.floor(row * blockSize + blockSize / 2);
        const idx = (py * offW + px) * 4;
        if (imgData.data[idx + 3] <= 128) continue;

        var rowFromBottom = logoGridH - 1 - row;
        var baseDelay = (rowFromBottom / logoGridH) * 0.3;
        var randomSpread = Math.random() * 0.35;
        var startTime = baseDelay + randomSpread;

        var angle = Math.random() * Math.PI * 2;
        var dist = 300 + Math.random() * 500;
        var originOffX = Math.cos(angle) * dist;
        var originOffY = Math.sin(angle) * dist + 200;

        logoBlocks.push({
          row: row, col: col,
          startTime: startTime,
          travelDuration: 0.2 + Math.random() * 0.15,
          originOffX: originOffX,
          originOffY: originOffY,
          rotation: (Math.random() - 0.5) * Math.PI * 2
        });
      }
    }

    logoBuildStartTime = performance.now() + logoBuildDelay;
  };
  logoImg.src = 'data:image/svg+xml;base64,' + btoa(logoSvg);

  function resize() {
    width = canvas.width = window.innerWidth;
    height = canvas.height = window.innerHeight;
  }
  resize();
  window.addEventListener('resize', resize);

  function draw() {
    ctx.fillStyle = 'rgba(64, 64, 65, 1)';
    ctx.fillRect(0, 0, width, height);

    if (logoBlocks && performance.now() > logoBuildStartTime) {
      var elapsed = performance.now() - logoBuildStartTime;
      var globalProgress = Math.min(elapsed / logoBuildDuration, 1);

      var logoDrawW = logoGridW * blockSize;
      var logoDrawH = logoGridH * blockSize;
      var scale = Math.min(width * 0.7 / logoDrawW, height * 0.65 / logoDrawH, 3.5);
      var offsetX = (width - logoDrawW * scale) / 2;
      var offsetY = (height - logoDrawH * scale) / 2;
      var bSize = blockSize * scale;
      var gap = scale * 0.8;
      var halfBlock = (bSize - gap * 2) / 2;

      var extrudeDepth = 12;
      var exStepX = 1.2;
      var exStepY = -1.0;

      /* Pre-compute block states */
      var blockStates = [];
      for (var i = 0; i < logoBlocks.length; i++) {
        var b = logoBlocks[i];
        if (globalProgress < b.startTime) {
          blockStates.push(null);
          continue;
        }

        var localRaw = Math.min((globalProgress - b.startTime) / b.travelDuration, 1);
        var t = 1 - Math.pow(1 - localRaw, 3);
        var landed = localRaw >= 1;

        var finalX = offsetX + b.col * bSize;
        var finalY = offsetY + b.row * bSize;
        var currentX = finalX + b.originOffX * (1 - t);
        var currentY = finalY + b.originOffY * (1 - t);
        var currentRot = b.rotation * (1 - t);
        var alpha = Math.min(t * 1.5, 1) * 0.35;

        blockStates.push({
          currentX: currentX, currentY: currentY,
          currentRot: currentRot, alpha: alpha,
          landed: landed, t: t
        });
      }

      /* Pass 1: Extrusion layers for landed blocks */
      for (var layer = extrudeDepth; layer >= 1; layer--) {
        var lx = layer * exStepX;
        var ly = layer * exStepY;
        var layerBrightness = 1 - (layer / extrudeDepth) * 0.7;
        var r = Math.floor(160 * layerBrightness);
        var g = Math.floor(65 * layerBrightness);
        var b2 = Math.floor(10 * layerBrightness);

        for (var j = 0; j < logoBlocks.length; j++) {
          var s = blockStates[j];
          if (!s || !s.landed) continue;

          var x = s.currentX + gap + halfBlock + lx;
          var y = s.currentY + gap + halfBlock + ly;

          ctx.fillStyle = 'rgba(' + r + ', ' + g + ', ' + b2 + ', ' + (s.alpha * 0.9).toFixed(3) + ')';
          ctx.fillRect(x - halfBlock, y - halfBlock, halfBlock * 2, halfBlock * 2);
        }
      }

      /* Pass 2: Front face for landed blocks */
      for (var k = 0; k < logoBlocks.length; k++) {
        var s2 = blockStates[k];
        if (!s2 || !s2.landed) continue;

        var cx = s2.currentX + gap + halfBlock;
        var cy = s2.currentY + gap + halfBlock;

        var rowN = logoBlocks[k].row;
        var colN = logoBlocks[k].col;
        var highlight = 1 + (1 - rowN / logoGridH) * 0.2 + (1 - colN / logoGridW) * 0.1;
        var fr = Math.min(Math.floor(255 * highlight), 255);
        var fg = Math.min(Math.floor(115 * highlight), 170);
        var fb = Math.min(Math.floor(30 * highlight), 70);

        ctx.fillStyle = 'rgba(' + fr + ', ' + fg + ', ' + fb + ', ' + s2.alpha.toFixed(3) + ')';
        ctx.fillRect(cx - halfBlock, cy - halfBlock, halfBlock * 2, halfBlock * 2);
      }

      /* Pass 3: In-flight blocks */
      for (var m = 0; m < logoBlocks.length; m++) {
        var s3 = blockStates[m];
        if (!s3 || s3.landed) continue;

        var depth = halfBlock * 0.5;

        ctx.save();
        ctx.translate(s3.currentX + gap + halfBlock, s3.currentY + gap + halfBlock);
        ctx.rotate(s3.currentRot);

        ctx.fillStyle = 'rgba(160, 70, 15, ' + s3.alpha.toFixed(3) + ')';
        ctx.beginPath();
        ctx.moveTo(halfBlock, -halfBlock);
        ctx.lineTo(halfBlock + depth * 0.5, -halfBlock - depth * 0.4);
        ctx.lineTo(halfBlock + depth * 0.5, halfBlock - depth * 0.4);
        ctx.lineTo(halfBlock, halfBlock);
        ctx.closePath();
        ctx.fill();

        ctx.fillStyle = 'rgba(255, 150, 60, ' + (s3.alpha * 0.8).toFixed(3) + ')';
        ctx.beginPath();
        ctx.moveTo(-halfBlock, -halfBlock);
        ctx.lineTo(-halfBlock + depth * 0.5, -halfBlock - depth * 0.4);
        ctx.lineTo(halfBlock + depth * 0.5, -halfBlock - depth * 0.4);
        ctx.lineTo(halfBlock, -halfBlock);
        ctx.closePath();
        ctx.fill();

        ctx.fillStyle = 'rgba(255, 115, 30, ' + s3.alpha.toFixed(3) + ')';
        ctx.fillRect(-halfBlock, -halfBlock, halfBlock * 2, halfBlock * 2);

        ctx.restore();
      }
    }

    requestAnimationFrame(draw);
  }

  draw();
})();
/* THEMELI — Animated Stat Counters */

(function initCounters() {
  var counters = document.querySelectorAll('.stat-number[data-target]');
  if (!counters.length) return;

  var observer = new IntersectionObserver(function (entries) {
    entries.forEach(function (entry) {
      if (!entry.isIntersecting) return;

      var el = entry.target;
      var target = parseInt(el.dataset.target, 10);
      var duration = 2000;
      var start = performance.now();

      function update(now) {
        var elapsed = now - start;
        var progress = Math.min(elapsed / duration, 1);
        var eased = 1 - Math.pow(1 - progress, 3);
        el.textContent = Math.floor(eased * target);

        if (progress < 1) {
          requestAnimationFrame(update);
        } else {
          el.textContent = target;
        }
      }

      requestAnimationFrame(update);
      observer.unobserve(el);
    });
  }, { threshold: 0.5 });

  counters.forEach(function (c) { observer.observe(c); });
})();
